### PR TITLE
Files for MO reflectivity operator test

### PR DESCRIPTION
**Pull request by ctgh**
## Description

Files for MO reflectivity operator test.

build-group=https://github.com/JCSDA-internal/ufo/pull/3414

### CODE REVIEW

**Review by fcvdb — APPROVED** [review]
Thanks Chris!

**Comment by huishao-r** [comment]
@gthompsnJCSDA Could you please take a look? We need two approvals. This is needed by the UFO PR.

**Review by gthompsnJCSDA — APPROVED** [review]
I hit approve, however, I am wondering why you would have a reflectivity data file with ObsValue of almost all 1.0 dBZ with no real variation as well as columns of model data (geovals) that are all minute `qrain` (1.E-8 up to about 1.E-6) that all produce a value of around 1-2 dBZ.  If that's what is desired fine, but up to 2 or more orders of magnitude Qrain delta is seemingly having almost no impact to the reflectivity.  What if you put something realistic in there like 1.E-4 (kg/kg) as another test?  I assume you have reason to believe the science is right, but it's rather uninteresting example and hard to know what it would do in real-life use case with real rain reflectivity as well as model qrain (or ice).

**Comment by ctgh** [comment]
@gthompsnJCSDA Thanks for your review! The obs values and errors in that file are all placeholders because it is just used to test the operator. The values of qrain and qice are real, but the constants used to deduce H(x) have been modified from our internal numbers. That produces the slightly artificial values you are seeing. However, this is a technical test of the operator and it demonstrates it is working correctly.

**Pull request merged**
