### PR TITLE
Update satellite VarBC files for new format

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
## Description

Update the satbias files to follow the new file format convention.
this is required for ufo PR:
https://github.com/JCSDA-internal/ufo/pull/3021

## Issue(s) addressed

Resolves #2993

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
Does anyone want to approve this or should I just merge it?

**Review by ADCollard — APPROVED** [review]

**Comment by huishao-r** [comment]
I had some failures yesterday. Testing with the updated sprint branch.

**Review by BenjaminRuston — APPROVED** [review]
these updated files are working correctly with associated UFO branch

**Review by huishao-r — APPROVED** [review]

**Comment by huishao-r** [comment]
Finally got everything passed here. Thanks for making these changes!

**Pull request merged**
