### PR TITLE
Test data for ObsFunction of conventional humidity observation error assignment

### PR DESCRIPTION
**Pull request by FanHan-NOAA**
## Description

Test data for UFO PR [#1927](https://github.com/JCSDA-internal/ufo/pull/1927). The test data contains radiosonde specific humidity IODA observations sampled over the globe and associated GeoVals file (temperature and pressures). 

### Issue(s) addressed

- partly fixes JCSDA-internal/ufo/issues/1914

## Acceptance Criteria (Definition of Done)

Ctest for the new ObsFunction passes.

## Dependencies

Please merge the following PR after this one. 

- [ ] waiting on approval of JCSDA-internal/ufo/pull/1927

## Impact

None

### CODE REVIEW

**Comment by emilyhcliu** [comment]
@CoryMartin-NOAA do you think we could begin to use JEDI convention for the observation data?
For example:
 */specific_humidity  ---> */specificHumidity 
MetaData/station_elevation ----> MetaData/stationElevation
MetaData/station_id -----> station_id -----> stationIdentification
MetaData/air_pressure ----->  pressure
MetaData/dateTime should be seconds since 2020-12-14T20:30:00Z
@FanHan-NOAA did you create the obs file through gsi-ncdiag from ioda-converters?

**Comment by FanHan-NOAA** [comment]
@emilyhcliu I used ioda-converters to generate some sondes data (ioda-obs & geovals) from ncdiag*nc4, then I ran `test_ObsFilters.x` with these data to generate new outputs (ioda-obs & geovals) to be used as test data. Below is the yaml I used. 

```
window begin: 2020-12-14T20:30:00Z
window end: 2020-12-15T03:30:00Z

observations:
- obs space:
    name: test_convhumidity_inflation
    obsdatain:
      obsfile: sondes_q_obs_ncdiag.nc4
    obsdataout:
      obsfile: sondes_q_obs_testdata.nc4
    simulated variables: [specific_humidity]
  geovals:
    filename: sondes_q_geoval_ncdiag.nc4
  obs operator:
    name: VertInterp
  obs filters:
    - filter: GOMsaver
      filename: sondes_q_geoval_testdata.nc4
    # Assign RH error
    - filter: Perform Action
      filter variables:
      - name: specific_humidity
      action:
        name: assign error
        error parameter: 0.2 #20% RH
    # Adjust error with forecast saturation specific humidity
    - filter: Perform Action
      filter variables:
      - name: specific_humidity
      action:
        name: inflate error
        inflation variable:
          name: ObsErrorFactorConvHumidity@ObsFunction
          options:
            pressure: MetaData/air_pressure
  passedBenchmark: 19324
```
The `sondes_q_obs_ncdiag.nc4` and `sondes_q_geoval_ncdiag.nc4` are input files from ioda-converters. The `sondes_q_obs_testdata.nc4` and `sondes_q_geoval_testdata.nc4` are output files I used as test data **here** after running `test_ObsFilters.x`. There is a new variable generated in the output obs file, `TestReference/error_inflation_factor`; it contains the error inflation factor output from the new ObsFunction. The new variable writeout is realized via the source code (temporary, only for test purpose).

**Comment by CoryMartin-NOAA** [comment]
@emilyhcliu no we can't yet because UFO is not set up to use those names

**Review by CoryMartin-NOAA — APPROVED** [review]

**Review by gthompsnJCSDA — APPROVED** [review]
I approve.  In the future, another and perhaps simpler and smaller file solution is just to write 3 different variables into a single obs file for your test reference variables.  And you can just name them with 1, 2, and 3 if needed.  There is some cost overheads of having 3 files where one can do the job with multiple reference variable internally.

Also in the future, if you name the feature branch in ufo-data the same as in the feature branch in ufo, then CI-testing will match up the two branches and your ctests would likely all pass.  A lot of reviewers see the non-passing tests and skip to review the PR until you resolve those errors.

**Comment by FanHan-NOAA** [comment]
> I approve. In the future, another and perhaps simpler and smaller file solution is just to write 3 different variables into a single obs file for your test reference variables. And you can just name them with 1, 2, and 3 if needed. There is some cost overheads of having 3 files where one can do the job with multiple reference variable internally.
> 
> Also in the future, if you name the feature branch in ufo-data the same as in the feature branch in ufo, then CI-testing will match up the two branches and your ctests would likely all pass. A lot of reviewers see the non-passing tests and skip to review the PR until you resolve those errors.

Thanks for these useful tips, especially the last one!

**Review by rhoneyager — APPROVED** [review]

**Pull request merged**
