### PR TITLE
SPRINT: Updates to fix remaining rttov tests that were failing

### PR DESCRIPTION
**Pull request by mikecooke77**
## Description

This PR updates two files manually.

1. testinput_tier_1/atms_n20_obs_20191230T0000_rttov_bad_data.nc4 - the satelliteIdentifier was a float and has been converted to an int.
2. testinput_tier_1/obs_ssmis_onedvar_20210701T1200Z.nc4 - the rain_flag used in the ctest has been changed to rainFlag.  This is only used in the yaml not in the code.

### Issue(s) addressed

None specified

## Acceptance Criteria (Definition of Done)

rttov ctests passing in ufo.

## Dependencies

To be merged with the following ufo change:
- [x] https://github.com/JCSDA-internal/ufo/pull/2494

To be merged after:
- [ ] #262 

## Impact

RTTOV related ctests now all pass.

### CODE REVIEW

**Review by smnewman — APPROVED** [review]
I can see the two integer variables (`satelliteIdentifier`, `rainFlag`) in the updated files. On the basis that ctests now pass, happy to approve.

**Comment by mikecooke77** [comment]
I have just merged gregs last change in and this required me to reconstitute the changes previously made.  I can confirm they are the same as before.

**Review by gthompsnJCSDA — APPROVED** [review]

**Comment by mikecooke77** [comment]
These files are updated by #262.  I will discuss with @neill-b the best way to integrate the changes.

**Comment by mikecooke77** [comment]
I have run @neill-b tool to upgrade to dateTime for the files.  They ctests still pass.  I will update the PR to make it clear that this should be merged after #262

**Pull request merged**
