### PR TITLE
geoval and obs files for testing active sensor module

### PR DESCRIPTION
**Pull request by imoradi**
## Description

This PR adds the geoval and observation files for testing the UFO active sensor  using CloudSat CPR
added in UFO PR: https://github.com/JCSDA-internal/ufo/pull/2954

## Issue(s) addressed

Resolves #<issue_number>

## Dependencies

List the other PRs that this PR is dependent on:

- UFO PR under the same name

## Impact

This does not have any impact on any other repository

## Checklist

- [x]  I have performed a self-review of my own code
- [x]  I have made corresponding changes to the documentation
- [x]  I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by PatNichols** [comment]
@imoradi the first file testinput_tier_1/instruments/radiance/cpr_cloudsat_geoval_2009113003.nc4 is a little large. Can it be reduced while still testing that the code works?

**Comment by imoradi** [comment]
> @imoradi the first file testinput_tier_1/instruments/radiance/cpr_cloudsat_geoval_2009113003.nc4 is a little large. Can it be reduced while still testing that the code works?

Yes we can keep whatever number of records make sense. That is not a problem for testing purposes. Do you want to test it and if it comes to the file size then we can take care of it either way.

**Comment by imoradi** [comment]
@PatNichols I reduced the file size to half. I hope this works.

**Review by PatNichols — APPROVED** [review]
Thanks @imoradi . the files sizes are great.

**Comment by imoradi** [comment]
@huishao-r @BenjaminRuston Any chance that we can go ahead and merge this one? Thank you!

**Review by BenjaminRuston — APPROVED** [review]
thanks @imoradi main verification I preformed besides passing ctests is are the file sizes sufficiently small and they are

**Pull request merged**
