### PR TITLE
Sprint:  eliminate deprecated variables from SPRINT, fix numerous files, VarMetaData group gone

### PR DESCRIPTION
**Pull request by gthompsnJCSDA**
## Description

This PR is needed for naming conventions sprint.  Over 100 files that previously had group `VarMetaData` have been updated along with removal by editing CDL files of any deprecated variables and dimensions (`nrecs`, `nvars` in particular).  The changed files will help get more Ctests in UFO to pass because individual variable names were inspected in the CDL files and changed where appropriate.  All prior adjustments specific to UKMO changes should also be kept intact with the exception of @JoanneAWaller variable for `surfacePressure` which needs to be made into `pressureSurface` for purposes of the `ObsSpace.yaml` file.  A corresponding update to that YAML file was submitted as PR in IODA along with any added variables to conform to naming conventions.

FYI: a big thanks to @mikecooke77 because he automated the move of variables from VarMetaData to MetaData which made editing 100+ CDL files created by `ncdump` a lot easier to clean up the remaining deprecated items.

### Issue(s) addressed

It is anticipated this update to testinput_tier_1 files should permit many more Ctests to pass with proper inspection of variable names and moving numerous variables from group `VarMetaData` into `MetaData`.  No separate issue was written for these changes.

## Acceptance Criteria (Definition of Done)

Lots more passing Ctests with edited yamls and source codes in UFO having been finished over the Sprint.

## Dependencies

Please be certain to merge #246  soon after merging this PR.

The `ObsSpace.yaml` file in IODA was changed in a PR with the same branch name - but there is no immediate dependency of one with the other.

## Impact

There should be no impact to other repos as long as kept in the Sprint branch.

### CODE REVIEW

**Comment by mikecooke77** [comment]
I don't think we should change to `pressureSurface` because this is at odds with other names in the convention. Surely `surfacePressure` makes more sense. As far as I understand it @JoanneAWaller  has already made most of the surface changes manually and this would require a large code change in UFO to a name that is at odds with the naming convention.

@JoanneAWaller could you comment.

**Comment by gthompsnJCSDA** [comment]
> I don't think we should change to `pressureSurface` because this is at odds with other names in the convention. Surely `surfacePressure` makes more sense. As far as I understand it @JoanneAWaller has already made most of the surface changes manually and this would require a large code change in UFO to a name that is at odds with the naming convention.
> 
> @JoanneAWaller could you comment.


Actually I can make a solution that keeps `surfacePressure` and I emailed Jo directly about it just in case she did anything to start the code changes (I hope not). Sorry for this back-and-forth.

**Comment by huishao-r** [comment]
@gthompsnJCSDA Is this surface pressure issue blocking this PR? I want to see whether we can get this merged as early as possible.

**Comment by JoanneAWaller** [comment]
Hi All, Just to say that I didn't make any changes to the code to use pressureSurface. @gthompsnJCSDA and I agreed that we can keep surfacePressure, and a simple change to the ObsSpace.yaml will allow this. As mentioned by @mikecooke77 I already made most of the `surface_pressure` to `surfacePressure` changes manually to code, data files and yamls. I think there are a couple of other yamls, but I am dealing with these now.

**Comment by gthompsnJCSDA** [comment]
> @gthompsnJCSDA Is this surface pressure issue blocking this PR? I want to see whether we can get this merged as early as possible.


No blockers at this time.  I reverted back the two files that I changed so it should work properly with Jo's efforts in code/yaml.  If I missed any (I hope not), we can quickly fix any.

**Review by huishao-r — APPROVED** [review]

**Comment by huishao-r** [comment]
We need one more approval to get this merged.

**Review by neill-b — APPROVED** [review]
I haven't been able to look at them all, but the changes that I've inspected look good.

**Pull request merged**
