### PR TITLE
Data required for 2D data change to DrawValueFromFile

### PR DESCRIPTION
**Pull request by neill-b**
## Description

Code changes have been planned to allow GNSS-RO observations to be read in 2D data.  This change enables the observation uncertainties to work with this data.  This is done by extending `DrawValueFromFile` to enable more flexible handling of the `channels` option.  The main data change to fix some of the missing value assignment (via _FillValue).

### Issue(s) addressed

See ufo change.

## Acceptance Criteria (Definition of Done)

Tests working correctly.

## Dependencies

- [x] waiting on https://github.com/JCSDA-internal/ufo/pull/2338
- [x] waiting on https://github.com/JCSDA-internal/ufo/pull/2364

## Impact

Must be merged together with
- [ ] ufo

### CODE REVIEW

**Review by ctgh — APPROVED** [review]
Happy to approve although would this be affected by the conventions sprint?

**Comment by neill-b** [comment]
> Happy to approve although would this be affected by the conventions sprint?

Yes.  I assume that I'll have some tricky merging to do once the sprint is complete.

**Comment by srherbener** [comment]
This was not merged with the companion PR in ufo: jcsda-internal/ufo/pull/2364

Will go ahead and merge now.

**Comment by neill-b** [comment]
Thanks @srherbener

**Pull request merged**
