### PR TITLE
Switch aircraft record to first dimension

### PR DESCRIPTION
**Pull request by mikecooke77**
## Description

This PR switches the aircraft bias file so the dimensions are [Record, Variable] rather than [Variable, Record].  This is the style agreed at this discussion () and it fixes some tests failures with debug builds which don't collapse the array dimensions.

## Issue(s) addressed

Resolves issues in ufo (e.g. https://github.com/JCSDA-internal/ufo/issues/3480)

## Dependencies

To be merged with the associated ufo PR:
- [ ] https://github.com/JCSDA-internal/ufo/pull/3500

## Impact

Ctests passing in debug builds.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation ( not needed)
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by mikecooke77** [comment]
@nicholasesposito I'm happy to wait for ioda-converters to merge this or it could go in before.  I'm don't mind either way.

**Comment by nicholasesposito** [comment]
@mikecooke77 Yeah go for it. I'm testing the change now. 
The issue is [iodaconv#1567](https://github.com/JCSDA-internal/ioda-converters/issues/1567)

**Review by nicholasesposito — APPROVED** [review]
My PR is linked.

**Review by BenjaminRuston — APPROVED** [review]
I approve this PR, thanks @mikecooke77

**Comment by mikecooke77** [comment]
I think given this change fixes code that is currently in broken and under research this pr is ok to go in before the ioda-converters change linked to this pr.

**Pull request merged**
