### PR TITLE
satwind_errnorm_filter

### PR DESCRIPTION
**Pull request by PatNichols**
satwind_errnorm_filter ufo-data

### CODE REVIEW

**Review by CoryMartin-NOAA — APPROVED** [review]

**Review by fabiolrdiniz — APPROVED** [review]
Thanks, @PatNichols!

**Review by hailingz — APPROVED** [review]

**Comment by CoryMartin-NOAA** [comment]
wait, isn't the issue that this is failing in develop? I approved without realizing what this PR is doing.

**Comment by fabiolrdiniz** [comment]
Should be the other way around. The branch merging into develop.

**Comment by fabiolrdiniz** [comment]
Shouldn't be like this one? https://github.com/JCSDA-internal/ufo-data/pull/322

**Pull request merged**
