### PR TITLE
Change geoval ordering to top to bottom and rename vertical coords

### PR DESCRIPTION
**Pull request by james-cotton**
## Description

Change the GeoVaL ordering to be from top to bottom. Switch to use air_pressure_levels_minus_one  and geopotential_height_levels_minus_one as the vertical coordinates for the winds by removing the extra pressure level and renaming the variables.

I have also added some cut down test files for use in unit tests to improve the code coverage. There are small versions of the geovals and obs file with only 10 observations. I have also added a small version with the geovals in the reverse (i.e. wrong) order.

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes ufo 1812

## Acceptance Criteria (Definition of Done)

All existing ctest pass

## Dependencies

Merge with:
- [ ] waiting on JCSDA-internal/ufo/pull/1832

## Impact

Please list the other repositories (if any) that this PR will require changes in (example below)

- [ ] ufo

### CODE REVIEW

**Review by ss421 — APPROVED** [review]
Looks good to me. 

I've checked that the data has been flipped. I see that `air_pressure_levels_minus_one` replaces `air_pressure_levels`. I have not run the ufo ctests however. Happy to do that but it seems that will be done as part of the PR CI.

One thing I did notice is that the data files contain both `nlevelsA` and `nlevelsB`. Is that still required - they are the same now but it may make sense to make the distinction for `theta` and rho levels.

**Comment by james-cotton** [comment]
> Looks good to me.
> 
> I've checked that the data has been flipped. I see that `air_pressure_levels_minus_one` replaces `air_pressure_levels`. I have not run the ufo ctests however. Happy to do that but it seems that will be done as part of the PR CI.
> 
> One thing I did notice is that the data files contain both `nlevelsA` and `nlevelsB`. Is that still required - they are the same now but it may make sense to make the distinction for `theta` and rho levels.

Thanks @ss421. Yes the ctests are run as part of the ufo CI. I thought about changing both nlevelsA and nlevelsB to be e.g. nlevs, since they are both the same (70). However as you say, it does indicate that they are a different level set so there appears to be no harm in leaving them as they are.

**Comment by mo-hlawrence** [comment]
This looks fine to me - I've had a good look at the files and as far as I can tell they seem right. I can also see that the ufo ctests are passing on the equivalent ufo PR. One thing I wondered is that the main geoval file seems quite large - larger than any other geoval file in testinput I think. So I wondered if you could whittle it down at some point by removing any unnecessary variables (ice_area_fraction?) and/or reducing the number of obs e.g. to something of the order hundreds rather than thousands? But maybe there's a reason for it being like this and anyway I'm still happy to approve this PR.

**Review by mo-hlawrence — APPROVED** [review]

**Comment by james-cotton** [comment]
> This looks fine to me - I've had a good look at the files and as far as I can tell they seem right. I can also see that the ufo ctests are passing on the equivalent ufo PR. One thing I wondered is that the main geoval file seems quite large - larger than any other geoval file in testinput I think. So I wondered if you could whittle it down at some point by removing any unnecessary variables (ice_area_fraction?) and/or reducing the number of obs e.g. to something of the order hundreds rather than thousands? But maybe there's a reason for it being like this and anyway I'm still happy to approve this PR.

Hi Heather, thanks for checking the files. Yes the main GeoVaL and obs files are large and could be trimmed down at some point. These files are a single time slot of GOES-16 winds which I did to ensure I captured all the different available channels for testing purposes, since there is no way to control what is extracted from the metdb. Perhaps some of the netcdf utilities can be used to grab smaller samples of each channel from within the bigger file.

**Pull request merged**
