### PR TITLE
SPRINT: Update profile QC netCDF files

### PR DESCRIPTION
**Pull request by ctgh**
Update profile QC netCDF files to follow the new conventions

Dependencies:

To be merged after:
- [ ] #262

### CODE REVIEW

**Comment by BenjaminRuston** [comment]
@ctgh can you, or would you like me to close this PR and delete the branch.  It is no longer needed correct?

**Comment by mikecooke77** [comment]
Note will be affected by #262 changes

**Comment by BenjaminRuston** [comment]
@ctgh is this deprecated now?  if so can close PR (and delete branch if you're being extra thorough)

**Comment by ctgh** [comment]
@BenjaminRuston Yes I think this can be closed. There are still a couple of profile QC checks that need to be fixed but most of the files in this PR are out of date.

**Pull request closed without merging**
