### PR TITLE
adding cris-fsr testing files

### PR DESCRIPTION
**Pull request by gmao-wgu**
## Description
Adding cris-fsr_n20 testing files for support new ufo filters testing

### CODE REVIEW

**Review by danholdaway — APPROVED** [review]

**Review by gmao-jjin3 — APPROVED** [review]

**Review by huishao-r — COMMENTED** [review]
Didn't look at the size of the data. Approve by assuming it is ok

**Review by BenjaminRuston — DISMISSED** [review]
@gmao-wgu could you reduce the size of the obs file from 100 points to 10 points?  It's a bit large. then can merge this and the associated UFO PR #2166

**Comment by gmao-wgu** [comment]
> @gmao-wgu could you reduce the size of the obs file from 100 points to 10 points? It's a bit large. then can merge this and the associated UFO PR #2166

Sure. I will work on it. Thanks!

**Comment by PatNichols** [comment]
@BenjaminRuston are you satisfied with the file sizes?

**Pull request merged**
