### PR TITLE
Sprint: Update data files for Met Office GNSS-RO

### PR DESCRIPTION
**Pull request by neill-b**
## Description

These file changes are required for the associated ufo pull request (https://github.com/JCSDA-internal/ufo/pull/2458).  They should allow the "bendmetoffice" ctests to run successfully.

### Issue(s) addressed

None

## Acceptance Criteria (Definition of Done)

Code and data merged, and ctests working

## Dependencies

None

## Impact

- [ ] ufo: required for https://github.com/JCSDA-internal/ufo/pull/2458

### CODE REVIEW

**Review by huishao-r — COMMENTED** [review]
recordNumber needs to be changed to sequenceNumber. pin @gthompsnJCSDA since he is doing the mass change to most of the obs data. Need to check whether it conflicts with his latest changes.

**Review by BenjaminRuston — COMMENTED** [review]
isn't the PR supposed to merge into `feature/sprint-ioda-converters`

**Comment by neill-b** [comment]
I've merged in @gthompsnJCSDA's branch.  However, I have chosen to keep my local files (as I have moved probability_gross_error to it's own group and changed the name, and quality_flags was not picked up).  Apart from those differences the files are the same.

**Comment by neill-b** [comment]
As agreed at the meeting, I've merged these changes into Mike's branch, so this PR is no longer required.

**Pull request closed without merging**
