### PR TITLE
Feature/satwind pressure errors

### LINKED ISSUE #42: Add satwind pressure errors and update TestReference U/V obs errors
## Description
The current Met Office satwind obs file, `satwind_obs_1d_2020100106_noinv.nc4`, contains TestReference values for eastward_wind and northward_wind. These contain U and V observation errors as calculated by the OPS for comparison with those calculated by ufo. At the moment the TestReference errors have been calculated assuming a constant 100 hPa pressure error estimate for each observation. 

We now wish to update these TestReference values using pressure errors which are vertically interpolated from a pressure-dependent error profile which can vary by satellite and channel.

The updated `TestReference/eastward_wind` and `TestReference/northward_wind` values are set using error profiles for `MetaData/satwind_id` values of "GOES16ir112" and "GOES16ir38". All others are assigned a default error profile. 

The error profiles are stored in a new file, `satwind_pressure_errors.nc4`.

## Dependencies
https://github.com/JCSDA-internal/ufo/issues/861

### PR DESCRIPTION
**Pull request by james-cotton**
## Description

This PR updates the TestReference/eastward_wind and TestReference/northward_wind values in satwind_obs_1d_2020100106_noinv.nc4.

It also adds a new file, satwind_pressure_errors.nc4, containing pressure error estimates for use in the individual observation errors scheme.

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #42 

## Dependencies

If there are PRs that need to be merged before or along with this one, please add "waiting for another PR" label and list the dependencies in the other repositories (example below). Note that the branches in the other repositories should have matching names for the automated tests to pass.
Waiting on the following PRs:
- [ ] waiting on JCSDA-internal/ufo/pull/1414

## Impact

Please list the other repositories (if any) that this PR will require changes in (example below)

- [ ] ufo

### CODE REVIEW

**Comment by james-cotton** [comment]
Note this PR and https://github.com/JCSDA-internal/ufo/pull/1414 need to be merged together.

**Review by ctgh — APPROVED** [review]
I assume these files are ready for review - let me know if not.
(By the way, the ufo PR depends on this one but in theory this one doesn't depend on ufo.)

**Comment by james-cotton** [comment]
> I assume these files are ready for review - let me know if not.
> (By the way, the ufo PR depends on this one but in theory this one doesn't depend on ufo.)

Thanks Chris, yes these are ready for review I just hadn't assigned anyone yet! This doesn't depend on the ufo one directly, but if it is merged before then the existing ctest will fail. I followed the text in the template under "dependencies" which says "If there are PRs that need to be merged before or along with this one,.. etc" so thought it best to add to be on the safe side.

**Comment by ctgh** [comment]
Makes perfect sense, thanks for explaining.

**Pull request merged**
