### PR TITLE
Update radiance test data to fix the scan_angle_order dimension size issue

### PR DESCRIPTION
**Pull request by srherbener**
## Description

This PR contains new radiance obs files that were created by re-running the ioda upgrader on the corresponding ioda v1 files. This was done to rebuild the scan_angle_order variables that had issues with their shapes not matching their dimension sizes.

### Issue(s) addressed

- fixes jcsda-internal/ufo#1395

## Acceptance Criteria (Definition of Done)

ufo tier2 tests all pass (as well as all other ufo tests of course).

## Dependencies

Waiting on the following PRs:
- [x] waiting on https://github.com/JCSDA-internal/ufo/pull/1402

## Impact

None

### CODE REVIEW

**Comment by srherbener** [comment]
Since there isn't a corresponding ufo PR, there are no CI tests running on this change. We should probably test on several systems before merging this PR. I'm trying my iMac now. Please feel free to add to the list below for testing.

Verify that ufo tests (tier1 and tier2) pass using develop branches for code and this PR's branch for ufo test data.
- [x] Mac (Big Sur 11.5, Clang 12.0.0, GNU Fortran 11.1.0_1)

**Review by shlyaeva — APPROVED** [review]
Tested on mac with clang, the tests that used to fail now pass for me. Thank you @srherbener!

I also opened https://github.com/JCSDA-internal/ufo/pull/1402 to check whether all tier2 tests would pass with this branch in all CIs.

**Comment by srherbener** [comment]
> Tested on mac with clang, the tests that used to fail now pass for me. Thank you @srherbener!
> 
> I also opened [JCSDA-internal/ufo#1402](https://github.com/JCSDA-internal/ufo/pull/1402) to check whether all tier2 tests would pass with this branch in all CIs.

Thanks for doing this testing @shlyaeva!

**Comment by fabiolrdiniz** [comment]
I just closed https://github.com/JCSDA-internal/ufo/pull/1402 because all tests have passed.

**Comment by srherbener** [comment]
> I just closed [JCSDA-internal/ufo#1402](https://github.com/JCSDA-internal/ufo/pull/1402) because all tests have passed.

Great! I'll merge this in now.

**Comment by fabiolrdiniz** [comment]
Just to register here that all tests passed on Orion with `jedi/gnu-openmpi/10.2.0`.

**Comment by srherbener** [comment]
Great! Thanks for testing this and letting us know.

**Pull request merged**
