### PR TITLE
Renamed profile QC files

### PR DESCRIPTION
**Pull request by ctgh**
Files for JCSDA-internal/ufo#1227

Two changes have been made:
- the files have been renamed, 
- any hard-coded instances of the JEDI missing float value have been replaced by "_".

### CODE REVIEW

**Review by shlyaeva — APPROVED** [review]

**Review by neill-b — COMMENTED** [review]
I'm happy with the general renaming.  However, I am confused by the missing data change.  I guess that you have replaced the previous missing value (-3.368795e+38) with numpy.nan?  I had understood it was preferred to use a fill-value instead (such as the netCDF fill value of 9.9692099683868690e+36 which you pointed me to previously).

**Comment by ctgh** [comment]
@neill-b I modified the values outside of python:
- output the file to text with `ncdump -p9,17`
- using linux tools, search and replace `-3.368795e+38` with `_`
- recreate the file with `ncgen`

I didn't explicitly set a fill value. Maybe I should do that instead of the above procedure?

**Comment by neill-b** [comment]
@ctgh Honestly I don't know.  My memory is that we should prefer a fill value for missing data, but my memory is often wrong. @srherbener - Is there a preference for using `_` or a fill value for missing data in a netCDF file?  Thanks

**Comment by srherbener** [comment]
> @neill-b I modified the values outside of python:
> 
> * output the file to text with `ncdump -p9,17`
> * using linux tools, search and replace `-3.368795e+38` with `_`
> * recreate the file with `ncgen`
> 
> I didn't explicitly set a fill value. Maybe I should do that instead of the above procedure?

This procedure should have resulted in the files containing the appropriate (by data type) default fill value wherever you replaced a value with a `_`.  (ncgen will set the default fill value wherever an `_` appears.) This can be confirmed by running ncdump on the modified file to see if the `_` characters are still where you expect them.  (ncdump reports fill values by printing a `_` instead of the actual value.) The ioda reader wants fill values set for all variables, and will recognize the default fill values (created by this procedure) and replace them with the internal JEDI missing values.

**Comment by ctgh** [comment]
@srherbener Thanks for the explanation. I can confirm that (when running ncdump) `_` appears wherever it is expected, so the fact that I didn't set fill values explicitly just means the defaults were used.

**Comment by srherbener** [comment]
> @srherbener Thanks for the explanation. I can confirm that (when running ncdump) `_` appears wherever it is expected, so the fact that I didn't set fill values explicitly just means the defaults were used.

Correct.

**Review by neill-b — APPROVED** [review]
Thanks for the explanation @srherbener.  Happy to approve these changes. :-)

**Comment by ctgh** [comment]
@neill-b Thanks!

**Pull request merged**
