### PR TITLE
File for Met Office Duplicate Check

### PR DESCRIPTION
**Pull request by ctgh**
## Description

File for Met Office Duplicate Check

Please merge at the same time as JCSDA-internal/ufo#2722

### CODE REVIEW

**Comment by ctgh** [comment]
@BenjaminRuston @PatNichols I believe the ufo-data repository will be frozen today in preparation for the release. If possible can you please merge this PR before that occurs? The new file contains test data for the linked ufo PR.

**Review by BenjaminRuston — APPROVED** [review]
do not see a problem getting this in file size seems reasonable

**Comment by BenjaminRuston** [comment]
@ctgh just this ufo-data PR, see the associated UFO PR has not yet been reviewed you would just like this ufo-date PR merged?

**Comment by ctgh** [comment]
@BenjaminRuston Thanks for the very quick review. Given the deadline would you mind merging this now, please? I hope to get the ufo PR reviewed by Met Office colleagues today. (I believe the deadline for the ufo freeze is next Wednesday?)

**Pull request merged**
