### PR TITLE
Adding MOPITT CO test files for UFO test

### PR DESCRIPTION
**Pull request by jeromebarre**
## Description

Adding MOPITT CO test files for UFO test.

Geovals were derived from the lam cmaq file that is already in the fv3-jedi-data files. 
OmF show significant differences. It could be updated in the future with a better quality model field maybe.

### Issue(s) addressed

[JCSDA-internal/ufo#1779](https://github.com/JCSDA-internal/ufo/issues/1779)
[JCSDA-internal/ioda-converters#733](https://github.com/JCSDA-internal/ioda-converters/issues/733)
JCSDA-internal/ioda#570

## Dependencies

ufo
ufo-data

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
@jeromebarre I think you meant to add reviewers and not assignees :-)

**Review by CoryMartin-NOAA — APPROVED** [review]

**Review by mpagowski — APPROVED** [review]
I looked at several geoval files and see that in that some units are provided, in some not.
Is there a convention that the units will always be standard? Would it inflate files significantly
if the units were provided?
BTW: what are CO units in the geoval file?

**Comment by BenjaminRuston** [comment]
@rhoneyager  I think this ones ready for merge

**Comment by BenjaminRuston** [comment]
thinking we can address @mpagowski  comment in the conventions sprint?

@rhoneyager should we open a sub-epic for the sprint?

**Comment by jeromebarre** [comment]
@mpagowski @BenjaminRuston the problem of geoval units is more a UFO problem than a IODA problem and if not a JEDI interface problem. So I wouldn't address this in this PR.
https://github.com/JCSDA-internal/ufo/issues/1841
The geoval unit is dependent on the background (that is model dependent). After discussing in this in various JEDI meetings it feels like the correct thing to do is to perform the unit conversion on the state. Using VADER maybe. @shlyaeva might help clarifying things on this as well.

**Pull request merged**
