### PR TITLE
Sprint: reverting 61 files back to branch sprint-ioda-converters-greg3 because Channel vector of files in primary sprint branch mistakenly got filled with all zero values. This should correct.

### PR DESCRIPTION
**Pull request by gthompsnJCSDA**
## Description

During Sprint week, the ioda-upgrade.x program mistakenly caused 61 files with Channel variable to become a vector of all zeroes.  The `feature/sprint-ioda-converters-greg3` branch contained the correctly fixed files so this PR brings them back into the primary sprint branch so more ctests should work properly.

### Issue(s) addressed

One was not needed/created.

## Acceptance Criteria (Definition of Done)

Positive review and demonstrates a number of passing ctests just by fixing the testinput_tier_1 files

## Dependencies

None

## Impact

None as long as kept in the sprint branch before merge later.

### CODE REVIEW

**Review by mikecooke77 — CHANGES_REQUESTED** [review]
You are absolutely correct Greg.  I'm very sorry for this error.  I was trying to fix the upgrader to preserve the iodav1 to iodav2 conversion and made a mistake in it.  I have corrected this locally now.

I also found seven files which were missed by this revert which have been updated and can be found in this branch:  [feature/sprint-ioda-converters-gregFix-mikeAdditions ](https://github.com/JCSDA-internal/ufo-data/tree/feature/sprint-ioda-converters-gregFix-mikeAdditions)

Could you merge this branch into yours before we commit this back to sprint-ioda-converters?

**Comment by gthompsnJCSDA** [comment]
@mikecooke77   OK, I can bring your 7 file addition into my branch.  Which branch of IODA do you have the code fix for the upgrader?  I would like to try doing all testinput_tier_2 files today (if possible).

**Comment by mikecooke77** [comment]
The upgrader you have will do exactly the same job. I haven't pushed the one I'm working on yet as it's not replicating the v1 to V2 performance. There will be no difference for this code sprint changes.

**Comment by gthompsnJCSDA** [comment]
> The upgrader you have will do exactly the same job. I haven't pushed the one I'm working on yet as it's not replicating the v1 to V2 performance. There will be no difference for this code sprint changes.


So the only way for me to work with the tier 2 files is to check out a previous commit hash number?  Since I have rebuilt the application with your change, it now makes my tier1 files with Channel vector filled with zero.  So there is no point for me to run that application on tier 2 files until you get time for fixing.

**Comment by mikecooke77** [comment]
> > The upgrader you have will do exactly the same job. I haven't pushed the one I'm working on yet as it's not replicating the v1 to V2 performance. There will be no difference for this code sprint changes.
> 
> So the only way for me to work with the tier 2 files is to check out a previous commit hash number? Since I have rebuilt the application with your change, it now makes my tier1 files with Channel vector filled with zero. So there is no point for me to run that application on tier 2 files until you get time for fixing.

Oh I see.  I have just pushed an update to feature/sprint-ioda-converters-fixupgrader.  Which will work.  Sorry my misunderstanding.

**Review by mikecooke77 — APPROVED** [review]
Thanks for making these changes Greg.  I have looked at a random selection of files and they look good to me.

**Review by huishao-r — APPROVED** [review]

**Pull request merged**
