### PR TITLE
New files for vertical average test

### PR DESCRIPTION
**Pull request by ctgh**
Add new files required for JCSDA-internal/ufo#1213. Please merge this at the same time as that PR.

### CODE REVIEW

**Review by shlyaeva — APPROVED** [review]
Thank you @ctgh !

**Comment by ctgh** [comment]
@adammartins has updated these files with underscores instead of the missing value.
I have started a new build in the accompanying ufo PR.

**Review by ldhawknesssmith — APPROVED** [review]
Ok Chris

**Review by srherbener — APPROVED** [review]
These files are using the netcdf fill value to mark missing values which is what we want. Thank you for updating this.

**Pull request merged**
