### PR TITLE
ioda-validate application

### LINKED ISSUE #116: Add CI testing for ufo-data
## Description

It's a good time to add some standalone tests to ufo data. In particular, once the ```ioda-validate``` program is ready we will want it to automatically run on new obs files in ufo-data. So, can we add in CI testing support for this repository?

### PR DESCRIPTION
**Pull request by rhoneyager**
## Description

See [ioda#566](https://github.com/JCSDA-internal/ioda/pull/566). Closes [ioda#549](https://github.com/JCSDA-internal/ioda/issue/549). Closes #116.

Depends on [ioda#566](https://github.com/JCSDA-internal/ioda/pull/566).

The ufo-data PR uses the new ```ioda-validate.x``` program to validate our obs test data files. The CMake code adds a test for each obs file.

All tests pass since the JEDI Data Conventions were just released, and we are not yet enforcing conventions. However, we will eventually change this and will need code sprints to update the files. By linking ufo-data with the CI system, we will be able to log which files need which changes.

### TODO in this PR
- [x] Add CI

### Sample ioda-validate.x report

The output will be colorized in a live run. Errors will be in red. Warnings will be in blue.

```
/Users/honeyage/usr/src/ioda-bundle/build/bin/ioda-validate.x "/Users/honeyage/usr/src/ioda-bundle/ioda/share/ioda/yaml/validation/ObsSpace.yaml" "/Users/honeyage/usr/src/ioda-bundle/iodaconv/test/testoutput/viirs_jpss1_oc_l2.nc"
Reading YAML from /Users/honeyage/usr/src/ioda-bundle/ioda/share/ioda/yaml/validation/ObsSpace.yaml
Processing data file: /Users/honeyage/usr/src/ioda-bundle/iodaconv/test/testoutput/viirs_jpss1_oc_l2.nc
 Verifying that all required groups exist
  ERROR: Required group Metadata is using an older name: 'MetaData'.
 Verifying group ObsValue
 Verifying group ObsError
 Verifying group MetaData
 Verifying group PreQC
 Verifying group /
  Warning: Attribute 'instrument' is present but is not listed as a required or optional attribute in the spec.
  Warning: Attribute 'processing_level' is present but is not listed as a required or optional attribute in the spec.
  Warning: Attribute 'date_time_string' is present but is not listed as a required or optional attribute in the spec.
  Warning: Attribute 'converter' is present but is not listed as a required or optional attribute in the spec.
  Warning: Attribute 'nlocs' is present but is not listed as a required or optional attribute in the spec.
  Warning: Attribute 'instrument' does not have a YAML spec.
  Warning: Attribute 'processing_level' does not have a YAML spec.
  Warning: Attribute 'date_time_string' does not have a YAML spec.
  Warning: Attribute 'converter' does not have a YAML spec.
 Verifying dimension names
  Warning: Dimension 'nlocs' is from an old standard. Prefer using the new name 'Location'.
 Verifying variable information
  Variable ObsValue/ocean_mass_content_of_particulate_organic_matter_expressed_as_carbon
   Warning: Variable 'ObsValue/ocean_mass_content_of_particulate_organic_matter_expressed_as_carbon' is not listed in the YAML conventions file.
  Variable ObsValue/mass_concentration_of_chlorophyll_in_sea_water
   Warning: Variable 'ObsValue/mass_concentration_of_chlorophyll_in_sea_water' is not listed in the YAML conventions file.
  Variable ObsError/ocean_mass_content_of_particulate_organic_matter_expressed_as_carbon
   Warning: Variable 'ObsError/ocean_mass_content_of_particulate_organic_matter_expressed_as_carbon' is not listed in the YAML conventions file.
  Variable ObsError/mass_concentration_of_chlorophyll_in_sea_water
   Warning: Variable 'ObsError/mass_concentration_of_chlorophyll_in_sea_water' is not listed in the YAML conventions file.
  Variable MetaData/datetime
  Variable MetaData/latitude
  Variable MetaData/longitude
  Variable PreQC/ocean_mass_content_of_particulate_organic_matter_expressed_as_carbon
   Warning: Variable 'PreQC/ocean_mass_content_of_particulate_organic_matter_expressed_as_carbon' is not listed in the YAML conventions file.
  Variable PreQC/mass_concentration_of_chlorophyll_in_sea_water
   Warning: Variable 'PreQC/mass_concentration_of_chlorophyll_in_sea_water' is not listed in the YAML conventions file.
Final results:
  # errors:      1
  # warnings:   16
```

### CODE REVIEW

**Review by gthompsnJCSDA — CHANGES_REQUESTED** [review]
It is difficult when reading the standard output to see a warning versus an error.  While I know you have color coded it, could you also just precede the line with either word: "Warning" or "Error" so when glancing down the left side it shows up quickly that way also?

**Comment by rhoneyager** [comment]
> It is difficult when reading the standard output to see a warning versus an error. While I know you have color coded it, could you also just precede the line with either word: "Warning" or "Error" so when glancing down the left side it shows up quickly that way also?

Sure. I just submitted a new commit in the ioda branch that addresses this.

**Comment by mer-a-o** [comment]
@rhoneyager I added ufo-data to ioda-bundle and tests are failing in ufo-data because it cannot find the yaml file. 
```
29: Test command: /JEDI/ioda-bundle/build/bin/ioda-validate.x "/validation/ObsSpace.yaml" "/JEDI/ioda-bundle/ufo-data/testinput_tier_1/amsua_metop-b_obs_2018041500_m.nc4"
29: Environment variables: 
29:  ECKIT_COLOUR_OUTPUT=1
29:  OMP_NUM_THREADS=1
29: Test timeout computed to be: 10000000
29: Reading YAML from /validation/ObsSpace.yaml
29: Exception: Cannot open /validation/ObsSpace.yaml  (No such file or directory)
29: Cannot open /validation/ObsSpace.yaml  (No such file or directory)
29: Final results:
29:   # errors:      1
29:   # warnings:    0
```
Am I missing something here? It looks like `find_package(ioda)` is not working properly?

**Comment by rhoneyager** [comment]
Thanks @mer-a-o. I can take a look. Apparently ecbuild on my mac is more recent than on CI (and ahead of the jedi stack). [This](https://github.com/JCSDA-internal/ioda/pull/566/commits/ced1979b4026210dfdac717d4ca0587cc106bcae) fixes it on Orion and hopefully it's the same bug with CI.

**Comment by rhoneyager** [comment]
@mer-a-o, in the [7cf526b build](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/469205354006/projects/ufo-data-internal-clang/build/ufo-data-internal-clang%3Adbf990fb-f1f0-46fc-9de7-4260bdba8208?region=us-east-1), Clang crashed when building oops. Does the new build process have enough memory?
```
[ 45%] Building CXX object oops/l95/src/executables/CMakeFiles/l95_diffstates.x.dir/DiffStates.cc.o
--
1054 | clang: error: unable to execute command: Killed
1055 | clang: error: clang frontend command failed due to signal (use -v to see invocation)
1056 | clang version 8.0.1-9 (tags/RELEASE_801/final)
1057 | Target: x86_64-pc-linux-gnu
1058 | Thread model: posix
1059 | InstalledDir: /usr/bin
1060 | clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
1061 | clang: note: diagnostic msg:
1062 | ********************
1063 |  
1064 | PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
1065 | Preprocessed source(s) and associated run script(s) are located at:
1066 | clang: note: diagnostic msg: /tmp/EDA-5759fd.cpp
1067 | clang: note: diagnostic msg: /tmp/EDA-5759fd.sh
1068 | clang: note: diagnostic msg:
1069 |  
1070 | ********************
```

**Comment by mer-a-o** [comment]
@rhoneyager I increased the memory and now build only ioda instead of ioda-bundle.

**Comment by mer-a-o** [comment]
Colorful output: https://cdash.jcsda.org/testDetails.php?test=4463791&build=52108. Nice!!

**Review by gthompsnJCSDA — APPROVED** [review]
I am not well-versed in all the CMake programming aspects so it's difficult for me to make any commentary on the coding structure or specifics.  It appears to do what it is intended to do and I think it is a valuable contribution to validate our test data files.  I see that one of the CI tests is failing, so I will conditionally approve the PR knowing that Ryan will get it to function.

**Comment by rhoneyager** [comment]
This has been painful to debug. It looks like a combination of two issues:

1. There seems to be a bug with the clang compiler itself. Exceptions are not being propagated between ioda and the application. An exception is raised but even though there is a ```catch``` block for it a ```SIGABRT``` is emitted instead. I can verify this using the Xcode debugger.
2. The files that trigger this exception are bad. For example, in ```obserror_4d.nc```, the ```channel_number@MetaData``` variable lists ```air_temperature@ErrorVariance``` as one of its dimensions. That is completely nonsensical, and it is why we throw the exception in the first place.

I have removed the bad files from the tests. Issue #120 was created for the affected files.

**Review by srherbener — APPROVED** [review]
Thanks for adding this. It will be great to have this check in place!

**Pull request merged**
