### PR TITLE
New GPM GMI geolval and observational files generated by GEOS.

### PR DESCRIPTION
**Pull request by gmao-jjin3**
New GMI data generated by GEOS which is conducted with the same CRTM as in JEDI. These data make it possible to validate UFO Hofx with GSI Hofx as shown in the PR https://github.com/JCSDA-internal/ufo/pull/1782.

### CODE REVIEW

**Review by rhoneyager — APPROVED** [review]

**Review by rhoneyager — CHANGES_REQUESTED** [review]
Test files are too large for tier 1. See comment in [the UFO PR](https://github.com/JCSDA-internal/ufo/pull/1782).

**Comment by huishao-r** [comment]
@gmao-jjin3 Would you please update the PR based on Ryan's comments?

**Comment by gmao-jjin3** [comment]
I'd like to keep the file as it is.  A shrank file is no longer useful for scientific validation or evaluation.

**Comment by huishao-r** [comment]
@gmao-jjin3 Is the data to be used for ctest? If so, ctest is only used to make sure the functionality is ok but not for scientific validation. We can' contain big data in the repositories given everybody is downloading those data from there. However, the full size data can be used locally for validation, but just not in ctest. We may have another layer of tests, which uses full size data but again the data storage will be handled differently.

**Comment by gmao-jjin3** [comment]
Couldn't push an update, so I made a new PR https://github.com/JCSDA-internal/ufo-data/pull/140.

**Comment by gmao-jjin3** [comment]
Updated data files are in the PR #145 .

**Comment by gmao-jjin3** [comment]
@gmao-yzhu Can you approve this PR? Thanks.

**Review by gmao-yzhu — APPROVED** [review]
The files look fine to me.

**Comment by gmao-jjin3** [comment]
GMI data sets are replaced with smaller files with 100 observations another PR. 
https://github.com/JCSDA-internal/ufo-data/pull/145

**Pull request closed without merging**
