### PR TITLE
Update the observations file and GeoVaLs file for radar reflectivity operator

### PR DESCRIPTION
**Pull request by gthompsnJCSDA**
## Description

This PR fixes the variable name (`reflectivity` instead of `dbz`) and removes extraneous variables from the observation file as well as substitutes the GeoVaLs file with original microphysics mixing ratios and number concentration that are not scaled.  There is a corresponding PR in ufo for these changes.

## Issue(s) addressed

Need to check if one was created by OU-CAPS persons supplying the first version of the data.

## Dependencies

Depends on [UFO PR 3115](https://github.com/JCSDA-internal/ufo/pull/3115)

## Impact

None expected.

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by junpark217** [comment]
Hi @gthompsnJCSDA  
I concur with the idea of changing the variable name.

However, I think that the geovals for options 108 and 109 might differ.
This is because the restored Qx from the scaled state variable does not exactly match the unscaled Qx.
Regarding the ctest, have you had a chance to run it for option 109 using the new geovalfile we provided?
Based on my understanding, I'm concerned that it may not pass with option 109.

I have sent this link to Chengsi . He will respond soon.
Thanks,

**Review by PatNichols — APPROVED** [review]
Looks good.

**Comment by gthompsnJCSDA** [comment]
> Looks good.

@PatNichols  This is on hold just another day or so.  Jun and Chengsi are providing another set of files again.

**Comment by PatNichols** [comment]
> > Looks good.
> 
> @PatNichols  This is on hold just another day or so.  Jun and Chengsi are providing another set of files again.
@gthompsnJCSDA 
Ok i will review if needed. Reviews here are purely based on file size and if they pass our rudimentary ctests so it may not need a new review. I try to be preemptive in reviews so that when we want to merge a ufo PR we are not waiting around for the ci tests to run

**Pull request merged**
