### PR TITLE
ctest data for jcsda-internal/ufo PR to add airTemperature gross check

### PR DESCRIPTION
**Pull request by BrettHoover-NOAA**
## Description

This PR provides ctest data for https://github.com/JCSDA-internal/ufo/pull/3178

## Issue(s) addressed

Resolves [jcsda-internal/ufo issue 3177](https://github.com/JCSDA-internal/ufo/issues/3177)

## Dependencies

List the other PRs that this PR is dependent on:
- [ ] [jcsda-internal/ufo PR 3178](https://github.com/JCSDA-internal/ufo/pull/3178)

## Impact

No impact on downstream repositories

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by PatNichols — APPROVED** [review]
Thanks

**Review by PatNichols — APPROVED** [review]
file sizes looks good

**Comment by BrettHoover-NOAA** [comment]
We should hold off on merging this until I do some more testing - it's possible that the obsfunction I wrote this for is redundant

**Comment by BrettHoover-NOAA** [comment]
closing this PR because https://github.com/JCSDA-internal/ufo/pull/3178 was also closed

**Pull request closed without merging**
