### PR TITLE
Update bias correction files to use new BC data file format and naming convention

### PR DESCRIPTION
**Pull request by huishao-r**
## Description

During the earlier VarBC code sprint, we decided to update the BC files with new format as well as following the IODA naming conventions. A upgrader developed already to convert bias coefficient files into the new format https://github.com/JCSDA-internal/ioda-converters/pull/1483. This PR has the data files updated by this upgrader. 

## Issue(s) addressed

Resolves UFO issues [#3242,](https://github.com/JCSDA-internal/ufo/issues/3242), [#3241](https://github.com/JCSDA-internal/ufo/issues/3241), [#3175](https://github.com/JCSDA-internal/ufo/issues/3175 )

## Dependencies

List the other PRs that this PR is dependent on:
- [ ] ...

## Impact

Expected impact on any test using these files (if yaml is not updated accordingly)

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by huishao-r** [comment]
Note: still waiting for CI ctest results so that we can identify the rest of data files to be updated. However, the files here in this PR have passed local ctests.

**Comment by huishao-r** [comment]
For conventional (e.g., aircraft) data, the BC files looks like: 
```
netcdf aircraft_artificial_bias {
dimensions:
	Record = 1 ;
	Variable = 4 ;
variables:
	string Variable(Variable) ;
	int Record(Record) ;

// global attributes:
		:_ioda_layout = "ObsGroup" ;
		:_ioda_layout_version = 0 ;

group: BiasCoefficients {
  variables:
  	float constant(Record, Variable) ;
  		constant:_FillValue = -3.368795e+38f ;
  	float cosineOfLatitudeTimesOrbitNode(Record, Variable) ;
  		cosineOfLatitudeTimesOrbitNode:_FillValue = -3.368795e+38f ;
  	float sineOfLatitude(Record, Variable) ;
  		sineOfLatitude:_FillValue = -3.368795e+38f ;
  } // group BiasCoefficients
}
```

**Comment by huishao-r** [comment]
for radiance (e.g., amsua), the BC files looks like:
```
netcdf satbias_amsua_n19 {
dimensions:
	Record = 1 ;
	Channel = 15 ;
variables:
	int sensorChannelNumber(Channel) ;
	int Record(Record) ;
	int numberObservationsUsed(Record, Channel) ;

// global attributes:
		:_ioda_layout = "ObsGroup" ;
		:_ioda_layout_version = 0 ;

group: BiasCoefficients {
  variables:
  	float constant(Record, Channel) ;
  		constant:_FillValue = -3.368795e+38f ;
  	float sensorZenithAngle(Record, Channel) ;
  		sensorZenithAngle:_FillValue = -3.368795e+38f ;
  	float cloudLiquidWater(Record, Channel) ;
  		cloudLiquidWater:_FillValue = -3.368795e+38f ;
  	float lapseRate_order_2(Record, Channel) ;
```
...
```
  } // group BiasCoefficients

group: BiasCoefficientErrors {
  variables:
  	float constant(Record, Channel) ;
  		constant:_FillValue = -3.368795e+38f ;
  	float sensorZenithAngle(Record, Channel) ;
  		sensorZenithAngle:_FillValue = -3.368795e+38f ;
  	float cloudLiquidWater(Record, Channel) ;
  		cloudLiquidWater:_FillValue = -3.368795e+38f
```

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by huishao-r** [comment]
@PatNichols the upgrader was updated, changing "emissivity" to "emissivityJacobian". Therefore, the data files here need another round update.

**Comment by mikecooke77** [comment]
I've just got the latest version of you branch Hui and when I do an ncdump on satbias_amsua_n19.2020110106.nc4 (others are similar) I am getting the incorrect naming e.g.

``` bash
netcdf satbias_amsua_n19.2020110106 {
dimensions:
	nrecs = 1 ;
	nvars = 15 ;
variables:
	int channels(nvars) ;
	int nrecs(nrecs) ;
	int nvars(nvars) ;

// global attributes:
		:_ioda_layout = "ObsGroup" ;
		:_ioda_layout_version = 0 ;
data:

 channels = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 ;

 nrecs = 0 ;

 nvars = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ;

group: biasCoefficients {
  variables:
  	float constant(nrecs, nvars) ;
  		constant:_FillValue = -3.368795e+38f ;
  	float zenith_angle(nrecs, nvars) ;
  		zenith_angle:_FillValue = -3.368795e+38f ;

```

e.g. `channels` should be `Channel`, the group `biasCoefficients` should be `BiasCoefficients` and the variable names in the groups are still the old names e.g. `zenith_angle`

**Review by mikecooke77 — DISMISSED** [review]
See comment

**Comment by mikecooke77** [comment]
> for radiance (e.g., amsua), the BC files looks like:
> 
> ```
> netcdf satbias_amsua_n19 {
> dimensions:
> 	Record = 1 ;
> 	Channel = 15 ;
> variables:
> 	int sensorChannelNumber(Channel) ;
> 	int Record(Record) ;
> 	int numberObservationsUsed(Record, Channel) ;
> 
> // global attributes:
> 		:_ioda_layout = "ObsGroup" ;
> 		:_ioda_layout_version = 0 ;
> 
> group: BiasCoefficients {
>   variables:
>   	float constant(Record, Channel) ;
>   		constant:_FillValue = -3.368795e+38f ;
>   	float sensorZenithAngle(Record, Channel) ;
>   		sensorZenithAngle:_FillValue = -3.368795e+38f ;
>   	float cloudLiquidWater(Record, Channel) ;
>   		cloudLiquidWater:_FillValue = -3.368795e+38f ;
>   	float lapseRate_order_2(Record, Channel) ;
> ```
> 
> ...
> 
> ```
>   } // group BiasCoefficients
> 
> group: BiasCoefficientErrors {
>   variables:
>   	float constant(Record, Channel) ;
>   		constant:_FillValue = -3.368795e+38f ;
>   	float sensorZenithAngle(Record, Channel) ;
>   		sensorZenithAngle:_FillValue = -3.368795e+38f ;
>   	float cloudLiquidWater(Record, Channel) ;
>   		cloudLiquidWater:_FillValue = -3.368795e+38f
> ```

I don't think this should be `sensorChannelNumber`.  If we are following ioda names this variable should match the dimension and be called `Channel`.  What is the role of `numberObservationsUsed` this is new to me and as far as I can see not in the ioda conventions.

**Comment by huishao-r** [comment]
@mikecooke77 Another team member was dedicated to update the ufo-data branch, beyond what I have tested. Unfortunately, it was not complete yet. "satbias_amsua_n19.nc4" is the one I used as an example for my tests.

**Comment by huishao-r** [comment]
> I don't think this should be `sensorChannelNumber`. If we are following ioda names this variable should match the dimension and be called `Channel`. What is the role of `numberObservationsUsed` this is new to me and as far as I can see not in the ioda conventions.


"Channel" was switched to "sensorChannelNumber" since this variable name is available in the IODA naming convention and we may only use selected channels instead of the full dimension. But we can talk about this in my proposed meeting (mentioned in the other PR). 

"numberObservationsUsed" is used in src/ufo/ObsBiasCovariance.cc. My understanding is this number is used to be compared with "minimalRequiredObsNumber" (input from yaml). If it is smaller than the required minimal number, the variance value will be changed/inflated

**Review by PatNichols — APPROVED** [review]

**Comment by PatNichols** [comment]
@mikecooke77 Do these changes look acceptable to you? We can now pass all ctests and this is ready to merge into the _sprint_ branch. Thank!

**Review by mikecooke77 — APPROVED** [review]
I've just ran all the ctests locally with our setup (this includes RTTOV and ROPP which is not currently in the CI) and all the ctests are passing.  Happy for this to go in.  Thanks for the work @huishao-r.

**Pull request merged**
