### PR TITLE
add new test obs files for onedvar ctest

### PR DESCRIPTION
**Pull request by brettcandy**
## Description

These files are reqiured to successfully run a new ctest for onedvar see ufo PR https://github.com/JCSDA-internal/ufo/pull/1709

## Acceptance Criteria (Definition of Done)

successful running of ufo ctest test_ufo_ssmis_ops_qc_rttovonedvarcheck

## Dependencies

None

### CODE REVIEW

**Review by smnewman — APPROVED** [review]

**Review by mikecooke77 — COMMENTED** [review]
geovals file:
There is `air_pressure_at_two_meters_above_surface` and `surface_pressure`.  These currently have different values.  I assume because `surface_pressure` contains pmsl.  Given the changes in ufo due soon could this be changed.

The fill values used in both files (e.g. ObsError/brightness_temperature) do not seem to be the jedi fill values (which I think they should be).  Have a look at: https://github.com/JCSDA-internal/oops/blob/develop/src/oops/util/missingValues.cc for how they are created.  You should get the same values in python if you use None as they are the default NetCDF fill values.

**Comment by brettcandy** [comment]
> geovals file: There is `air_pressure_at_two_meters_above_surface` and `surface_pressure`. These currently have different values. I assume because `surface_pressure` contains pmsl. Given the changes in ufo due soon could this be changed.
> 
> The fill values used in both files (e.g. ObsError/brightness_temperature) do not seem to be the jedi fill values (which I think they should be). Have a look at: https://github.com/JCSDA-internal/oops/blob/develop/src/oops/util/missingValues.cc for how they are created. You should get the same values in python if you use None as they are the default NetCDF fill values.

ok, but i dont really understand the problem as i am using the comparison suite to create these files. @smnewman can you advise. perhaps i need to upgrade my version of the comparison suite?

**Comment by brettcandy** [comment]
> 

Update -right i can see in other netcdf files what the values should be - will test with these new values in the comparison suite.

**Comment by brettcandy** [comment]
@mikecooke77 check my latest version of obs_ssmis_onedvar_20210701T1200Z.nc4 it now has correct fill values

**Comment by brettcandy** [comment]
@mikecooke77 i have also now ensured that surface_pressure and air_pressure_at_two_metres are consistent. Please check that this is ok. My current ssmis onedvar ctest passes with this change and the previous

**Comment by mikecooke77** [comment]
Brett,  Given the surface_pressure change I think it would be good to remove the air_pressure_at_two_meters.  Also I was thinking 1000 obs is probably too many for a quick ctest.  Perhaps 100 would be sufficient.

**Comment by brettcandy** [comment]
@mikecooke77 agreed 100 obs is fine and will be quicker to run. Ive updated this and associated yaml in ufo.

**Comment by mikecooke77** [comment]
Could you remove the "air_pressure_at_two_meters_above_surface" from the geovals and then happy to approve.

**Comment by brettcandy** [comment]
> Could you remove the "air_pressure_at_two_meters_above_surface" from the geovals and then happy to approve.

yes sorry - done! and tested!

**Review by mikecooke77 — APPROVED** [review]

**Pull request merged**
