### PR TITLE
Merge extra data files from develop to release branch

### PR DESCRIPTION
**Pull request by huishao-r**
## Description

Three more files were added from two PRs merged after the release branch was created last Friday. We have to fix this to avoid UFO develop conflicting with the UFO-data branch. All the data updates after the release branch was created should have pointed to the release branch, instead of develop.

### CODE REVIEW

**Review by BenjaminRuston — APPROVED** [review]
this looks correct thanks Hui

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
@huishao-r @mer-a-o I sent the updated tarball to the GDEX team. I'll let you know when I hear back so you can test again.

**Comment by climbfuji** [comment]
@huishao-r @mer-a-o the tarball has been updated on GDEX, please test again.

**Comment by mer-a-o** [comment]
@climbfuji @huishao-r All the ufo tests pass with the new database. Thanks.

**Pull request merged**
