### PR TITLE
Feature/ground based radar operator

### PR DESCRIPTION
**Pull request by PatNichols**
## Description

This adds the ufo-date for the ufo PR #2911 https://github.com/JCSDA-internal/ufo/pull/2911
build-group=https://github.com/JCSDA-internal/ufo/pull/2911

### CODE REVIEW

**Comment by PatNichols** [comment]
@junpark217 This is the ufo-data branch for your PR https://github.com/JCSDA-internal/ufo/pull/2911

**Comment by PatNichols** [comment]
@fcvdb or @fabiolrdiniz Could one of you approve this PR? It is well within the proper size and passed ctest. I can't approve it since I am the one who created it. Thank you!

**Review by fcvdb — APPROVED** [review]
Thanks Pat!

**Review by BenjaminRuston — APPROVED** [review]
thanks for the updates to the files the sizes are reasonable and work with the PR

**Pull request merged**
