### PR TITLE
All files present in ufo-data/testinput_tier_1 that are not used and can be deleted (929Mb)

### PR DESCRIPTION
**Pull request by fcvdb**
This PR has for objective to clean-up the `testinput_tier_1` directory of all unused test data files. 

130 files were identified and deleted. The complete list is attached as a text file. 

There's no dependency with this pull request. 

See issue issue UFO [#2052](https://github.com/JCSDA-internal/ufo/issues/2052) for details.

This PR encompass the files deleted in previous PR ufo-data [#182](https://github.com/JCSDA-internal/ufo-data/pull/182)), in which the 7 larger files only are deleted (891Mb). The remaining files to be deleted in this PR are smaller (38Mb). 

PR ufo-data [#182](https://github.com/JCSDA-internal/ufo-data/pull/182) can be skipped if this present PR is merged beforehand. There is not conflict between the two PRs. PR ufo-data [#182](https://github.com/JCSDA-internal/ufo-data/pull/182) was submitted as an intermediate step to limit the quantity of changes made at once.

[files_not_used.txt](https://github.com/JCSDA-internal/ufo-data/files/8998566/files_not_used.txt)

### CODE REVIEW

**Comment by shlyaeva** [comment]
I think mpas-jedi uses ufo-data repo for observation files in mpas tests. It would be good to check if any of the files removed here are used in mpas-jedi tests and need to be moved to mpas-jedi-data. @jjguerrette FYI.

**Comment by huishao-r** [comment]
Since this change might affect different applications, I suggest we don't rush this for this quarter release. But we need to continue this clean up and get this into develop (after code freeze).

**Comment by rhoneyager** [comment]
> I think mpas-jedi uses ufo-data repo for observation files in mpas tests. It would be good to check if any of the files removed here are used in mpas-jedi tests and need to be moved to mpas-jedi-data. @jjguerrette FYI.

I completely agree. ufo-data should only be used for ufo tests. We decoupled ioda-data & ufo-data for the same reason.

**Comment by jjguerrette** [comment]
Of the files removed, I think these are the ones that _need_ to be copied to mpas-jedi-data:
```
airs_aqua_obs_2018041500_m.nc4
cris-fsr_npp_obs_2018041500_m_qc.nc4
iasi_metop-a_obs_2018041500_m.nc4
```

As @rhoneyager indicates, we could copy all files needed for mpas-jedi to mpas-jedi-data.  Also I agree with @huishao-r that it would be best to go slow with this one.

**Comment by fcvdb** [comment]
Thanks @jjguerrette. I'll update the PR to keep those three files, so that they can be moved to the `mpas-jedi `later on. We have decided to postpone this change to a later time after the release.

**Comment by fcvdb** [comment]
I have updated for `mpas-jedi `the text files with the list of files to be deleted. It is attached.
[files_not_used.txt](https://github.com/JCSDA-internal/ufo-data/files/9002681/files_not_used.txt)

**Review by rhoneyager — APPROVED** [review]

**Comment by jjguerrette** [comment]
> ```
> airs_aqua_obs_2018041500_m.nc4
> cris-fsr_npp_obs_2018041500_m_qc.nc4
> iasi_metop-a_obs_2018041500_m.nc4
> ```

I made a mistake here.  `cris-fsr_npp_obs_2018041500_m_qc.nc4` should have been `cris-fsr_npp_obs_2018041500_m.nc4`.

**Comment by metdyn** [comment]
mpas-jedi  ctest failed, because

**`testinput_tier_1/cris-fsr_npp_obs_2018041500_m.nc4`** is deleted in this PR. 

This will affect all incoming PR in mpas-jedi, will you please add this file back?     Thanks!

https://github.com/JCSDA-internal/mpas-jedi/issues/748

**Pull request merged**
