### PR TITLE
[Bugfix] update sensorScanPosition from float to int (again)

### LINKED ISSUE #350: [Bug] mpas-jedi ctest fails with #343
## Current behavior (describe the bug)
Several mpas-jedi ctests use `airs_aqua_obs_2018041500_m.nc4`, `cris-fsr_npp_obs_2018041500_m.nc4`, and `iasi_metop-a_obs_2018041500_m.nc4`, but #343 did not consider those files.

https://github.com/JCSDA-internal/mpas-jedi/blob/develop/test/testinput/hofx3d.yaml#L157

https://github.com/JCSDA-internal/mpas-jedi/blob/develop/test/testinput/hofx3d.yaml#L175

https://github.com/JCSDA-internal/mpas-jedi/blob/develop/test/testinput/hofx3d.yaml#L193

## To Reproduce

> What computer are you running on?

Cheyenne

> What compilers/modules are you using?

gnu-openmpi, spack-stack v1.4.0

> Steps to reproduce the behavior

check out the mpas-bundle, build, run ctest

## Expected behavior
All mpas-jedi ctests pass.

### PR DESCRIPTION
**Pull request by gthompsnJCSDA**
## Description

Previously, I updated only those files that were actively involved in ci-testing within `ufo/test/*/CMakeLists.txt` however, that left some **not-updated** `testinput_tier_1` files that were used in MPAS-jedi  ctests.  Therefore, this PR now updates all remaining files containing `float sensorScanPosition` to integer per merged PRs in UFO, IODA, elsewhere.

## Issue(s) addressed

Resolves #350 

## Dependencies

None

## Impact

Possible impact to ctests in ufo repo but need to wait to see if any previously working tests now fail.

### CODE REVIEW

**Comment by fabiolrdiniz** [comment]
@byoung-joo, please, can you create a PR in mpas-jedi with a branch named `bugfix/sensorScanPosition_integer` to test these files? I can't create it over there, otherwise, I'd do it myself.

**Review by fabiolrdiniz — APPROVED** [review]
Thanks, @gthompsnJCSDA!

**Review by byoung-joo — APPROVED** [review]
Thanks, @gthompsnJCSDA . This fixes the issue. All mpas-jedi CI tests pass (https://github.com/JCSDA-internal/mpas-jedi/pull/904).

**Review by BenjaminRuston — APPROVED** [review]
thanks Greg and thank you @byoung-joo for pointing this out so quickly

**Pull request merged**
