### PR TITLE
Add reference data for CloudCostFunction ObsFunction

### PR DESCRIPTION
**Pull request by smnewman**
## Description

This PR adds TestReference data for CloudCostFunction ObsFunction with ATOVS/RTTOV-SCATT.

* `TestReference/cloud_cost` variable is added to `testinput_tier_1/atovs_metopb_obs_2021011512_rttov_scatt.nc4`
* Ordering of GeoVaLs is corrected (reversed) in `testinput_tier_1/geovals_atovs_20210115T1200Z_rttov_scatt.nc4`

## Acceptance Criteria (Definition of Done)

All ctests pass for corresponding ufo PR.

## Dependencies

PR should be merged along with:
- [ ] https://github.com/JCSDA-internal/ufo/pull/2022

## Impact

- [ ] ufo

### CODE REVIEW

**Review by mikecooke77 — COMMENTED** [review]
Could test reference data also be added for the atms ctest for this ObsFunction?

**Comment by smnewman** [comment]
> Could test reference data also be added for the atms ctest for this ObsFunction?

There is already `TestReference/cloud_cost` in `atms_obs_20200401T0000Z_10locs.nc4` for the ctest `test_ufo_function_cloudcostfunction` for ATMS. Is that what you mean?

**Comment by mikecooke77** [comment]
Ah OK.  I've just re-read the ufo test.  All good for me then I'll approve.

**Review by mikecooke77 — APPROVED** [review]

**Review by brettcandy — APPROVED** [review]
looks fine to me.

**Pull request merged**
