### PR TITLE
Add new netcdf for AMV QI processing

### LINKED ISSUE #46: Add new netcdf for new AMV QI processing filter
## Description
Add new netcdf. New netcdf is a small amount of amv data with some additional variables to compare in test for https://github.com/JCSDA-internal/ufo/issues/1346

### PR DESCRIPTION
**Pull request by adammartins**
## Description

Add new amv netcdf for amv_QI_processing filter in ufo https://github.com/JCSDA-internal/ufo/pull/1439

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #46

### CODE REVIEW

**Comment by wsmigaj** [comment]
I see that each of the `wind_generating_application_...` variables contains only a single integer (apart from missing values). Judging by the implementation of the `ProcessAMVQI` filter, this doesn't need to be the case. Would it be worth making some of these variables hold a mixture of different integers to test the more general case?

**Comment by adammartins** [comment]
I've changed the first values in the wind_generating _application_1 and _2 and changed one of the missing values in wind_generating_applications_2 and percent_confidence_2 to a value in order to ensure the test goes into the if else statement, here: https://github.com/JCSDA-internal/ufo/pull/1439/commits/ff4c76142f77a4dbce2c4286e8f5752e7954da46#diff-195fb7b3f5f2ba9040719097ddfa27a0937360492109de67d715ee60d69a368bR136

**Review by james-cotton — APPROVED** [review]
Approved

**Review by wsmigaj — APPROVED** [review]

**Comment by adammartins** [comment]
Hi @mmiesch I think this PR is ready now.

**Pull request merged**
