### PR TITLE
Multi-level and single lever buddy check data

### PR DESCRIPTION
**Pull request by cpelley**
## Description

This PR adds input+reference for the multi-level buddy check.

### Issue(s) addressed

N/A

## Acceptance Criteria (Definition of Done)

The new files will be added.

## Dependencies

merge with https://github.com/JCSDA-internal/ufo/pull/1270

## Impact

N/A

## Test Data

N/A

### CODE REVIEW

**Review by wsmigaj — COMMENTED** [review]
Would it require a lot of work to make some records non-consecutive in one of the multi-level test cases? E.g. to reorder observations so that the first few belong to records 1, 2, 1, 2, 1, 2, 1 and 2.

**Comment by cpelley** [comment]
Apologies @wsmigaj for missing your comment.  I have added this new test file.

**Review by ctgh — APPROVED** [review]

**Review by wsmigaj — APPROVED** [review]
@cpelley Thank you very much for adding this extra test.

**Comment by cpelley** [comment]
@rhoneyager @srherbener would you be happy to merge?
Cheers

**Comment by cpelley** [comment]
Thanks @rhoneyager :)

**Pull request merged**
