### PR TITLE
Update amsr2 geolval and observational files

### PR DESCRIPTION
**Pull request by gmao-jjin3**
Update amsr2 geolval and observational files with additional rain and snow clouds. They are converted from GOES diagnostic files.

### CODE REVIEW

**Review by gmao-jjin3 — COMMENTED** [review]
New data files made from GEOS in which the same CRTM is used as in JEDI.

**Review by rhoneyager — CHANGES_REQUESTED** [review]
Same issue as with the GMI PR. Either we should move the affected test to tier 2 or should shrink the files considerably.

**Comment by gmao-jjin3** [comment]
@gmao-yzhu  Can you approve this ufo-data PR? Thanks.

**Review by gmao-yzhu — APPROVED** [review]
Look fine to me.

**Comment by gmao-jjin3** [comment]
> Same issue as with the GMI PR. Either we should move the affected test to tier 2 or should shrink the files considerably.

Both data are replaced by much smaller data sets.

**Comment by gmao-jjin3** [comment]
@rhoneyager Can you merge this PR? Thanks.

**Comment by gmao-jjin3** [comment]
> Same issue as with the GMI PR. Either we should move the affected test to tier 2 or should shrink the files considerably.

@rhoneyager  The original large files have been replaced, so are those GMI files. Can you merge these PRs?  Thanks.

**Review by HamidehGMAO — APPROVED** [review]

**Review by rhoneyager — APPROVED** [review]

**Pull request merged**
