### PR TITLE
add two files for soil interp test

### PR DESCRIPTION
**Pull request by weihuang-jedi**
## Description

Add dataset for nearest-neighbor ctest: ufo_test_tier1_test_ufo_nearest_neighbor_soil 

### Issue(s) addressed

This is to support addressing issue issue ufo #2302

## Acceptance Criteria (Definition of Done)

ctest: ufo_test_tier1_test_ufo_nearest_neighbor_soil  pass.

## Dependencies

None

## Impact

Please list the other repositories (if any) that this PR will require changes in (example below)

- [ ] ufo

### CODE REVIEW

**Review by frolovsa — APPROVED** [review]
I have not reviewed these files but this PR makes sense to me.

**Comment by zcstanley** [comment]
Wei and I discussed these files offline and their inclusion makes sense to me.

**Review by zcstanley — APPROVED** [review]
Sorry for accidentally closing the PR. Wei and I discussed these files offline and their inclusion makes sense to me.

**Review by shlyaeva — COMMENTED** [review]
It may be good to rename `letkf_hofx_smap_20191215.nc` to indicate that it's an obs file (since it's used for the ufo tests) and make the naming similar to other obs files.
Also, it may be good to remove some of the locations from these two files to make them smaller for the unit tests (smaller files + faster tests), similar to the number of obs in the other files.

**Comment by weihuang-jedi** [comment]
@Anna Shlyaeva ***@***.***> Your suggestion makes sense, so renamed
the input file as smap_smc_obs_20191215.nc.

**Pull request merged**
