### PR TITLE
SPRINT: Update the test files for the sprint

### PR DESCRIPTION
**Pull request by mikecooke77**
## Description

Revert changes to obsdiag and geovals as they do not need to be updated.
Amend some files that fail automated update.  
Update a whole bunch of additional files.

There looks like many more files changed but this is to do with the upgrade tool repeating the upgrade.

### Issue(s) addressed

None

## Acceptance Criteria (Definition of Done)

None

## Dependencies

None

## Impact

None

### CODE REVIEW

**Review by BenjaminRuston — APPROVED** [review]
here will get a count of how many PRs are passing

**Review by JoanneAWaller — APPROVED** [review]
Happy that my files are updated in here, and believe other files should be good!

**Review by JoanneAWaller — APPROVED** [review]

**Review by twsearle — APPROVED** [review]
These files were sufficient to pass tests in the UFO PRs I have made as part of the sprint (at time of writing). So I am very happy for these to go in!

**Comment by mikecooke77** [comment]
As far as I'm concerned this can go in.  The couple of met office prs left are still a work in progress and can be merged later.

**Pull request merged**
