### PR TITLE
Feature/add aircraft predictors

### PR DESCRIPTION
**Pull request by BrettHoover-NOAA**
## Description

Provides ctest data for testing `ObsMetaDataPredictor` function in JCSDA-internal/ufo/feature/add_aircraft_predictors

required for:
https://github.com/JCSDA-internal/ufo/pull/2979

## Issue(s) addressed

https://github.com/JCSDA-internal/ufo/issues/2149
https://github.com/JCSDA-internal/ufo/pull/2965
https://github.com/JCSDA-internal/ufo/pull/2979

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by PatNichols** [comment]
@BrettHoover-NOAA @BenjaminRuston Does the first file need to be so large to test the code in ufo? We would like it a little smalled <=1 MB. Sorry to be pain.

**Review by huishao-r — APPROVED** [review]

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by BrettHoover-NOAA** [comment]
@PatNichols I just tried running the ctest without having access to or making reference to `aircraft_geovals_20190801T0000Z_aircraft_predictors.nc4` and it still passes, I don't think we are touching the geovals file at all. @BenjaminRuston @CoryMartin-NOAA @huishao-r would it be acceptable to push a change to the ctest YAML in my ufo branch to remove references to the geovals file and remove the file entirely from this PR?

**Comment by CoryMartin-NOAA** [comment]
if it's not needed, I say toss it out!

**Comment by BrettHoover-NOAA** [comment]
geovals file was removed and ctest YAML in ufo branch was updated to not make reference to it

**Pull request merged**
