### PR TITLE
Remove broken pointers.

### LINKED ISSUE #423: Pointer errors on files
## Current behavior (describe the bug)

Doing git clone of ufo-data develop gives this at the end:

Encountered 2 file(s) that should have been pointers, but weren't:
	testinput_tier_1/geoval_goes16_glm_201905202300.nc
	testinput_tier_1/obs.goes16_glm.201905202300.nc

I'm guessing this isn't supposed to happen?

## To Reproduce

Run:

git clone https://github.com/JCSDA-internal/ufo-data

## Expected behavior

I think that message should not be there.

### PR DESCRIPTION
**Pull request by DJDavies2**
## Description

Removes a couple of files that caused "broken pointer" warnings.

I don't really understand what is wrong here, but removing the files seems to result in working ctests.  Can they just be removed?

Resolves #423

## Dependencies

None.

## Impact

None.

## Checklist

- [x ] I have performed a self-review of my own code
- [x ] I have made corresponding changes to the documentation
- [x ] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by ctgh** [comment]
These files are used in the ctests `test_ufo_opr_lightning` and `test_ufo_linopr_lightning` produced by @gthompsnJCSDA .
I am not sure why removing them did not cause those ctests to fail.

Googling the error message seems to indicate it is due to git lfs (see [here](https://stackoverflow.com/questions/46704572/git-error-encountered-7-files-that-should-have-been-pointers-but-werent)). There are some suggestions about how to fix it but I am not sure if any of them will work here.

**Comment by DJDavies2** [comment]
Okay, I have probably made a mistake somewhere.  Also this is a duplicate of https://github.com/JCSDA-internal/ufo-data/issues/428 addressed by https://github.com/JCSDA-internal/ufo-data/pull/429 so this is probably redundant.

**Comment by PatNichols** [comment]
@DJDavies2 Do we need to close this if we merge https://github.com/JCSDA-internal/ufo-data/pull/429 ?

**Comment by DJDavies2** [comment]
Yes, I think so.

**Comment by PatNichols** [comment]
Thanks @DJDavies2

**Pull request closed without merging**
