### PR TITLE
flip geovals for sattcwv so they are top down

### PR DESCRIPTION
**Pull request by mo-hlawrence**
## Description

Make changes to the geovals files used for SatTCWV ufo ctests in order to be consistent with the approach of top-down only geovals, as follows:

1. Change the 'sattcwv_geovals_20201230T0600Z.nc4' geovals file so that the geovals are ordered from the top down instead of the bottom up. This is to be used on the current ctest for SatTCWV, and is to be consistent with enforcing a top-down approach for model levels.

2. Add a new geovals file 'sattcwv_geovals_reversed_20201230T0600Z.nc4' which has the same geovals ordered from bottom to top. This is to be used in a new ctest to check that the sattcwv code fails when presented with bottom-up geovals.

### Issue(s) addressed

- first step towards fixing #1829

## Acceptance Criteria (Definition of Done)

Merged into develop.

## Dependencies

No dependencies as currently the sattcwv code accepts both top-down and bottom-up model fields (this will be changed in the future to accept only top-down). However this is linked to the ufo change: JCSDA-internal/ufo#1833

## Impact

There should be no impact. The following ufo ctests are affected (but I have checked that they still run):

- test_ufo_opr_sattcwv
- test_ufo_linopr_sattcwv

### CODE REVIEW

**Review by neill-b — APPROVED** [review]
Looks good.  I've checked the file out and flipped it back, and it compares with the current version.

**Comment by neill-b** [comment]
@mo-hlawrence could you add an "estimate" to this PR?  It helps to show JCSDA that we've been productive.

**Comment by neill-b** [comment]
BTW, you can't see the "Sprint" label because your PR is in the JEDI workspace.  If it were in the OBS workspace you'd be able to add the label.  Unfortunately, I don't think you can change workspace for this PR.

**Comment by mo-hlawrence** [comment]
> @mo-hlawrence could you add an "estimate" to this PR? It helps to show JCSDA that we've been productive.

Sorry I can't see 'estimate' anywhere...? Just milestones, labels, assignees, linked issues

**Comment by mo-hlawrence** [comment]
This change affects the following ufo ctests:
- test_ufo_opr_sattcwv
- test_ufo_linopr_sattcwv

I've checked they still work for the ufo develop branch with this new file, but it would be good if a reviewer could double-check.

When testing this in the met office system you will need to do 'unset  LOCAL_PATH_JEDI_TESTFILES' after loading the jopa module files, otherwise your build will pick up the develop ufo-data. Similarly you will need to comment out some lines of the ufo-bundle CMakeList to make sure it doesn't replace the ufo-data branch with develop.

**Review by ctgh — APPROVED** [review]
Thanks for adding this. I can confirm the relevant tests work with the reversed GeoVaLs.

**Comment by mo-hlawrence** [comment]
Ok I've worked out how to add an estimate now thanks to everybody's help.

**Review by james-cotton — APPROVED** [review]

**Comment by mo-hlawrence** [comment]
Ok I've added the new reversed file for the new ctest as discussed. So it's ready for new reviews now.

**Review by neill-b — APPROVED** [review]
Looks good, thanks Heather.

**Review by ctgh — APPROVED** [review]

**Pull request merged**
