### PR TITLE
updating cpr cloudsat obs to include layers

### PR DESCRIPTION
**Pull request by imoradi**
## Description

Provide a detailed description of what this PR does. What problem does it fix? What new capability does it add?

build-group=https://github.com/JCSDA-internal/ufo/pull/3246

## Issue(s) addressed

Current cpr_cloudsat test observation don't include multiple layers so this PR updates the test observations and geovals to include multiple layers which helps the development and testing process. This needs to be merged before the ufo changes to handle layers.

Resolves #<issue_number>

## Dependencies

List the other PRs that this PR is dependent on:
- [ ] ...

## Impact

Expected impact on downstream repositories:

## Checklist

- [ x] I have performed a self-review of my own code
- [ x] I have made corresponding changes to the documentation
- [x ] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by ctgh** [comment]
Thanks for adding this. Is there an associated ufo PR?

**Comment by imoradi** [comment]
> Thanks for adding this. Is there an associated ufo PR?

Yes I added you to that PR as well. The UFO PR fails of course unless this PR is merged with UFO-data.

**Comment by ctgh** [comment]
You can ensure the PRs are treated together as follows:

(1) In the description of this PR, add the line:
`build-group=https://github.com/JCSDA-internal/ufo/pull/3246`

(2) In the description of the ufo PR, add the line:
`build-group=https://github.com/JCSDA-internal/ufo-data/pull/406`

The build system should then automatically take both of the associated branches prior to compiling.
You may need to retrigger the build to ensure that works.

**Comment by imoradi** [comment]
Thank you very much, Chris @ctgh . I updated both PRs to point to each other. I hope this resolves the issue and they build successfully.

**Pull request closed without merging**
