### PR TITLE
Adding files for ufo lightning

### PR DESCRIPTION
**Pull request by rkong66**
## Description

This PR is a companion to the UFO new operator for GOES Lightning Mapper (GLM) flash extent density.

## Dependencies

Depends on [UFO PR 3074](https://github.com/JCSDA-internal/ufo/pull/3074)

## Impact
No impacts expected for other repos.

## Checklist
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by PatNichols — COMMENTED** [review]
Hi @rkong66 The filet testinput_tier_1/geoval_fed_201905202300.nc is around 4MB. Is it possible to reduce the size to below a MB? Thank you!

**Comment by rkong66** [comment]
> Hi @rkong66 The filet testinput_tier_1/geoval_fed_201905202300.nc is around 4MB. Is it possible to reduce the size to below a MB? Thank you!

@PatNichols Thank you, I will further reduce the file size.

**Review by PatNichols — APPROVED** [review]

**Review by PatNichols — APPROVED** [review]
File sizes look good.

**Comment by gthompsnJCSDA** [comment]
@rkong66   I updated the description and changed your data file to suit what is proper for the JEDI data conventions.  We already had a variable name for `lightningFlashExtent` and the abbreviation `fed` makes no sense to other persons.  I also eliminated a series of unnecessary or obsolete contents/variables in your file.  Please refer to the JEDI documentation for data conventions in future PRs.  Things like `nvars`, `nlocs`, `nrecs`, `VarMetaData` are all obsolete and I am guessing that `height` is not needed for this form of data as well as `stationIdentification` and so on.

While my changes will now break the UFO operator, I will work with you to update code(s) in a reasonable fashion to fix it quickly.

**Comment by rkong66** [comment]
> @rkong66 I updated the description and changed your data file to suit what is proper for the JEDI data conventions. We already had a variable name for `lightningFlashExtent` and the abbreviation `fed` makes no sense to other persons. I also eliminated a series of unnecessary or obsolete contents/variables in your file. Please refer to the JEDI documentation for data conventions in future PRs. Things like `nvars`, `nlocs`, `nrecs`, `VarMetaData` are all obsolete and I am guessing that `height` is not needed for this form of data as well as `stationIdentification` and so on.
> 
> While my changes will now break the UFO operator, I will work with you to update code(s) in a reasonable fashion to fix it quickly.

Thank you for the updates and the clarification regarding the JEDI data conventions. I acknowledge that some elements, such as 'stationIdentification', are unnecessary for the UFO and that my initial approach was influenced by other observation files I had referenced. This was due to my uncertainty about whether certain information was required for processing the observations. I will refer to the JEDI document and revise the observation names and make the necessary adjustments based on your feedback.

Since the lightning observation operator does not require vertical interpolation, the 'height' variable is indeed unnecessary for LETKF. For LETKF, vertical localization is conducted at pressure levels, hence only the ‘pressure’ information is required in the observation file. However, I am contemplating whether ‘height’ might still be relevant for MPAS-JEDI, which conducts vertical localization at model height levels. This consideration is why I retained the height information in the observation file.

**Comment by gthompsnJCSDA** [comment]
@rkong66  I believe the variable `MetaData/pressure` will do what is needed for vertical localization.  Also, I pushed my changes of your file directly into your feature branch, so you should just see that you are comfortable with my changes and let me know if you think I took away something critical.  Also, I renamed both your obs file and geovals file.  Trying to make it pretty clear overall.  Comment here please if you are good with my changes.

**Comment by rkong66** [comment]
> @rkong66 I believe the variable `MetaData/pressure` will do what is needed for vertical localization. Also, I pushed my changes of your file directly into your feature branch, so you should just see that you are comfortable with my changes and let me know if you think I took away something critical. Also, I renamed both your obs file and geovals file. Trying to make it pretty clear overall. Comment here please if you are good with my changes.

Thank you for the updates and the renaming of the observation and geovals files for clarity. The modifications look great.

**Review by PatNichols — APPROVED** [review]

**Review by BenjaminRuston — APPROVED** [review]
this is a great new capability thanks @rkong66

**Comment by rkong66** [comment]
> this is a great new capability thanks @rkong66

Thank you all for your great efforts; we truly appreciate it. @PatNichols @BenjaminRuston @gthompsnJCSDA

**Pull request merged**
