### PR TITLE
SPRINT: Tidy up 1dvar names

### PR DESCRIPTION
**Pull request by mikecooke77**
Names tidied up in TestReference and TestReferenceOneDVar so that ctests pass.

To be merged with:
- [ ] https://github.com/JCSDA-internal/ufo/pull/2549

All ufo ctests should pass:
- [x] are ufo ctests associated with the above ticket passing?

### CODE REVIEW

**Review by smnewman — APPROVED** [review]

**Comment by brettcandy** [comment]
can you check the file thats goneinto lfs correctly? i have downloaded it and get a failure if i try to perform ncdump
ncdump -h atms_n20_obs_20191230T0000_rttov.nc4 > new 
NetCDF: HDF error
Location: file ncdump.c; line 1705

**Comment by mikecooke77** [comment]
> can you check the file thats goneinto lfs correctly? i have downloaded it and get a failure if i try to perform ncdump ncdump -h atms_n20_obs_20191230T0000_rttov.nc4 > new NetCDF: HDF error Location: file ncdump.c; line 1705

It looks OK to me.  Could you try ncdump again on a new terminal window.  I've had conflicting hdf paths in the past that have caused this kind of issue.

**Comment by brettcandy** [comment]
> > can you check the file thats goneinto lfs correctly? i have downloaded it and get a failure if i try to perform ncdump ncdump -h atms_n20_obs_20191230T0000_rttov.nc4 > new NetCDF: HDF error Location: file ncdump.c; line 1705
> 
> It looks OK to me. Could you try ncdump again on a new terminal window. I've had conflicting hdf paths in the past that have caused this kind of issue.

Thanks Mike, that solved the issue. I have checked the three update files and confirmed via ncdump -h that the variable names follow the new convention and make sense

**Review by brettcandy — APPROVED** [review]
good to merge. Thanks for doing this

**Pull request merged**
