### PR TITLE
Add sensor zenith angle correction transform unit test file.

### PR DESCRIPTION
**Pull request by mikecooke77**
## Description

Adds a test file for the unit test which corrects the surface_emissivity using the Cal_SatZenithAngleCorrection variable transform added with ufo PR .  The test file contains the following:

nchans = 20 ;
nlocs = 100;
nvars = 20 ;

MetaData/datetime(nlocs) ;
MetaData/latitude(nlocs) ;
MetaData/longitude(nlocs) ;
MetaData/satellite_id(nlocs) ;
MetaData/sensor_zenith_angle(nlocs) ;
MetaData/surface_type(nlocs) ;
MetaData/time(nlocs) ;

ObsError/brightness_temperature(nlocs, nchans) 

ObsValue/brightness_temperature(nlocs, nchans) 

TestReference/surface_emissivity(nlocs, nchans) 

VarMetaData/surface_emissivity(nlocs, nchans) 
VarMetaData/variable_names(nvars)

### CODE REVIEW

**Comment by wsmigaj** [comment]
Some variables in the new file seem to use missing value indicators that don't match the `_FillValue` attribute -- for example, 
```
group: TestReference {
  variables:
        float surface_emissivity(nlocs, nchans) ;
                surface_emissivity:_FillValue = 9.96921e+36f ;
  data:

   surface_emissivity =
  -3.368795e+38, -3.368795e+38, -3.368795e+38, -3.368795e+38, 
      -3.368795e+38, -3.368795e+38, -3.368795e+38, -3.368795e+38, 
  ...
```

Is this intentional?

**Comment by mikecooke77** [comment]
> Some variables in the new file seem to use missing value indicators that don't match the `_FillValue` attribute -- for example,
> 
> ```
> group: TestReference {
>   variables:
>         float surface_emissivity(nlocs, nchans) ;
>                 surface_emissivity:_FillValue = 9.96921e+36f ;
>   data:
> 
>    surface_emissivity =
>   -3.368795e+38, -3.368795e+38, -3.368795e+38, -3.368795e+38, 
>       -3.368795e+38, -3.368795e+38, -3.368795e+38, -3.368795e+38, 
>   ...
> ```
> 
> Is this intentional?

Thanks for spotting this.  Changes have been made and the branch has been updated

**Review by wsmigaj — APPROVED** [review]
Thanks a lot for fixing the discrepancy between missing values and the `_FillValue` attribute.

One more thing I've noticed is that the file contains both the `MetaData/datetime` and `MetaData/time` variables -- I suppose one of them could be removed. But if they are consistent (I haven't checked if that's the case) the extra one doesn't do any harm.

**Comment by mikecooke77** [comment]
time has been removed as it was a non standard time and datetime seems to be the common name used in JEDI.  Thanks.

**Comment by wsmigaj** [comment]
@mikecooke77 Thank you!

**Review by smnewman — APPROVED** [review]

**Pull request merged**
