### PR TITLE
Data for RTTOV interface making use of qcflags

### PR DESCRIPTION
**Pull request by mikecooke77**
## Description

This adds a new array in the TestReference folder in an atms test file needed for https://github.com/JCSDA-internal/ufo/pull/3281.

## Issue(s) addressed

None specifically raised on ufo-data but partially solves https://github.com/JCSDA-internal/ufo/issues/3265

## Dependencies

Needs merging before or at the same time as: 
- [ ] https://github.com/JCSDA-internal/ufo/issues/3265

## Impact

ufo and ufo-data only

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by fcvdb — APPROVED** [review]
Thanks Mike!

**Review by PatNichols — APPROVED** [review]
Looks good

**Comment by gthompsnJCSDA** [comment]
@mikecooke77  Is it possible that we can remedy a couple more variables that do not match the naming conventions while doing this PR?  List of vars that I see in the file not yet accounted for in `ObsSpace.yaml` are the following:
```
MetaData/aapp_bennartz_index
MetaData/aapp_cirrus_index
MetaData/amsuscatindex
MetaData/surface_cost_fn
```
Also, is `MetaData/time` needed as well as `MetaData/dateTime` or could the former be eliminated (since it is marked deprecated in the conventions)?

Thanks.

**Comment by mikecooke77** [comment]
> @mikecooke77 Is it possible that we can remedy a couple more variables that do not match the naming conventions while doing this PR? List of vars that I see in the file not yet accounted for in `ObsSpace.yaml` are the following:
> 
> ```
> MetaData/aapp_bennartz_index
> MetaData/aapp_cirrus_index
> MetaData/amsuscatindex
> MetaData/surface_cost_fn
> ```
> 
> Also, is `MetaData/time` needed as well as `MetaData/dateTime` or could the former be eliminated (since it is marked deprecated in the conventions)?
> 
> Thanks.

Good idea.  I have run this through the upgrader and that has done the following conversions:

1. `MetaData/aapp_bennartz_index` to `MetaData/bennartzIndexAAPP`
2. `MetaData/aapp_cirrus_index` to `MetaData/cirrusIndexAAPP`

`MetaData/amsuscatindex` and `MetaData/surface_cost_fn` are not used anywhere in the code so have been removed.  By putting this through the upgrader it has also removed `MetaData/time`.

I have run all the testing locally and it passes (at the moment rttov is not in the ci)

**Comment by gthompsnJCSDA** [comment]
@mikecooke77  I did not know that the upgrader could remove any variables (`MetaData/time`) which doesn't really seem a good idea.  Super glad you could make these changes to conform to the data conventions.  We must get strict on new additions because we have a mountain of tech debt to eliminate a bunch of things in files that we allowed to pass through because the job to eliminate everything non-conforming will be large.

**Review by gthompsnJCSDA — APPROVED** [review]
Thanks Mike for the changes to data file.  Fully approve.

**Comment by mikecooke77** [comment]
> @mikecooke77 I did not know that the upgrader could remove any variables (`MetaData/time`) which doesn't really seem a good idea. Super glad you could make these changes to conform to the data conventions. We must get strict on new additions because we have a mountain of tech debt to eliminate a bunch of things in files that we allowed to pass through because the job to eliminate everything non-conforming will be large.

I think time is a special case in terms of removal.  The others were done by hand using ncdump and ncgen.

**Pull request merged**
