### PR TITLE
Add obs cygnss data for testing osw obsfunction

### PR DESCRIPTION
**Pull request by smaticka**
build-group=https://github.com/JCSDA-internal/ufo/pull/3173
## Description

For testing the `obs fuction`, a reduced obs file of `cygnss` data is provided in the `ufo-data`. 

See this PR for details (NEEDS TO MERGE AT SAME TIME): https://github.com/JCSDA-internal/ufo/pull/3173

## Issue(s) addressed

the obs function is used in the converters that address this issue (iodaconv): https://github.com/JCSDA-internal/ioda-converters/issues/1452

### CODE REVIEW

**Comment by smaticka** [comment]
closing b/c the data needs to exist in `fv3-jedi` where the ctest is.

**Comment by smaticka** [comment]
Opening again, b/c it turns out the ctest did belong in `ufo` and not `fve-jedi`

**Comment by smaticka** [comment]
This works now! Ready for review

**Review by fabiolrdiniz — DISMISSED** [review]
@smaticka, please, can you clean up your obs file? You have groups that don't "pertain" to a legit obs file (hofx, ObsBias, EffectiveQC, etc.). You can have a look at your very first file (the original used as input to get geovals) and keep only those groups and the new reference groups for the test.

**Review by fabiolrdiniz — APPROVED** [review]
Thanks, @smaticka!

**Review by fcvdb — APPROVED** [review]
Thanks Sam!

**Review by huishao-r — APPROVED** [review]

**Review by PatNichols — APPROVED** [review]

**Pull request merged**
