### PR TITLE
Storing GOES-16 GLM files using git lfs

### LINKED ISSUE #428: [Bug] Git complains about GOES-16 GLM files
Git complains about GOES-16 GLM files (recently added) with the following message after cloning the repo:

```console
Encountered 2 files that should have been pointers, but weren't:
	testinput_tier_1/geoval_goes16_glm_201905202300.nc
	testinput_tier_1/obs.goes16_glm.201905202300.nc
```

### PR DESCRIPTION
**Pull request by fabiolrdiniz**
## Description
Storing GOES-16 GLM files using git lfs.

## Issue(s) addressed
Resolves https://github.com/JCSDA-internal/ufo-data/issues/428

## Dependencies
None.

## Impact
None.

## Checklist
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by gthompsnJCSDA — APPROVED** [review]
Approved based on the premise that ctests pass.  But since I added these files a few weeks ago, what did I do incorrectly that made the problem happen so that I can avoid the same from happening in the future?

**Comment by fabiolrdiniz** [comment]
@gthompsnJCSDA, I suspect you added the files from a place where you haven't git lfs installed (s4? derecho? etc.). Is that the case?

**Review by PatNichols — APPROVED** [review]
looks good @fabiolrdiniz

**Comment by gthompsnJCSDA** [comment]
> @gthompsnJCSDA, I suspect you added the files from a place where you haven't git lfs installed (s4? derecho? etc.). Is that the case?

Nope. I used Hercules per my typical route.  So however these things get set incorrectly, it would be good to know to avoid a future repeat.

**Pull request merged**
