### PR TITLE
release/skylab-v4: Update version to 1.6.0 in CMakeLists.txt

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

See title

### CODE REVIEW

**Comment by climbfuji** [comment]
@huishao-r Please review/approve, thanks!

**Review by huishao-r — APPROVED** [review]

**Comment by huishao-r** [comment]
@climbfuji When I checked out the release branch for ufo-data, I have one failed ctest, which shows that
`ufo-data/testinput_tier_1/instruments/conventional` is missing
`sondes_uv_obs_2020121500.nc4`
compared with develop

**Comment by climbfuji** [comment]
Take a look here: https://github.com/JCSDA-internal/ufo-data/compare/release/skylab-v4?expand=1 - I see no difference other than the version in `CMakeLists.txt`. 

But look at this: https://github.com/JCSDA-internal/ufo-data/compare/release/skylab-v4...develop?expand=1

So somebody merged into develop *after* the release branch was created. I informed everyone on the JCSDA core channel when the release branch was created, so that PR should have been redirected into release/skylab-v4 instead of develop.

**Comment by huishao-r** [comment]
Yes. You are right. I'll inform OBS again about this!!

**Comment by huishao-r** [comment]
@climbfuji Should I create a PR to merge the develop change to this release branch? Thanks for figuring it out. Our fault.

**Comment by climbfuji** [comment]
Yes, that will work. However, we'll need to update the tarball and ask the GDEX people to upload it again.

**Pull request merged**
