### PR TITLE
Add MetaData/surfaceQualifier

### LINKED ISSUE #361: Add MetaData/surfaceQualifier to scatwind obs file
## Description
Add MetaData/surfaceQualifier to scatwind obs file for use in the observation operator test.

### PR DESCRIPTION
**Pull request by james-cotton**
## Description

This PR is simply to add a new variable, `MetaData/surfaceQualifier`, to one of the scatwind obs files. This is needed for https://github.com/JCSDA-internal/ufo/pull/2991 but has null impact on existing tests so can be merged ahead of that change.

Performing a diff on the file with nccmp shows only this difference
DIFFER : Failed to find variable surfaceQualifier in file "/downloads/scatwind_obs_1d_2020100106.nc4".
where /downloads/scatwind_obs_1d_2020100106.nc4 is the old file from develop.

## Issue(s) addressed

Resolves #361 

## Dependencies

None

## Impact

None

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by PatNichols — COMMENTED** [review]
@james-cotton This file is almost 2 MB. Is it possible to reduce the size? Thank you!

**Comment by james-cotton** [comment]
@PatNichols Yes we can reduce this file! However we will also need to reduce a couple of other related files and modify some yaml. Is it OK if I do that in a new PR?

**Comment by PatNichols** [comment]
@james-cotton that will be okay. Sorry to be a pain.

**Review by PatNichols — APPROVED** [review]
thanks

**Comment by james-cotton** [comment]
> @james-cotton that will be okay. Sorry to be a pain.

@PatNichols No problem! I have created the PR here https://github.com/JCSDA-internal/ufo-data/pull/363

**Pull request merged**
