### PR TITLE
Data for average temperature filter

### PR DESCRIPTION
**Pull request by neill-b**
## Description

A new filter to calculate the average temperature below a certain height has been requested:
https://github.com/JCSDA-internal/ufo/pull/2338
This change provides the extra data files that are needed by this PR.

### Issue(s) addressed

See ufo PR.

## Acceptance Criteria (Definition of Done)

ufo code running and tests passing

## Dependencies

None - this is new data, so does not need to wait for ufo PR.

## Impact

Needed for ufo PR.

### CODE REVIEW

**Review by orlewis — CHANGES_REQUESTED** [review]
Both of these files contain the history of the netCDF file changes. I think this can causes segmentation faults see https://github.com/JCSDA-internal/ufo-data/pull/137 where this has been addressed before.

**Comment by neill-b** [comment]
@orlewis - thanks, sorted in latest commit.

**Review by orlewis — APPROVED** [review]

**Review by mikecooke77 — COMMENTED** [review]
It looks like you are using time.  Why not dateTime with all the same conventions as in the ObsSpace?

**Comment by neill-b** [comment]
Thanks @mikecooke77, I had kept with `time` as these files were derived from some much older files.  However, with a bit of fiddling I've managed to change to `dateTime`.  I've also had to update one of the entries in TestReference since the denominator was incorrectly set as an `int`.

**Review by james-cotton — APPROVED** [review]

**Pull request merged**
