### PR TITLE
Sprint groundgnss, aod, sattcwv, gauss thin and stringmanip test data changes

### PR DESCRIPTION
**Pull request by orlewis**
## Description

Updates test data for the naming conventions sprint. Test data that are being updated are:
Ground GNSS observations
AOD Met Office
Sattcwv
Gauss thinning Met Office
string manipulation filter

## Acceptance Criteria (Definition of Done)

Ctests associated with these files pass. 

## Dependencies

- [x] waiting on JCSDA-internal/ufo/pull/2459
- [x] waiting on JCSDA-internal/ufo-data/pull/260

## Impact

Please list the other repositories (if any) that this PR will require changes in (example below)

- [ ] ufo

### CODE REVIEW

**Review by mikecooke77 — CHANGES_REQUESTED** [review]
Most files are failing the valiator with:
ERROR: Variable 'MetaData/time' is deprecated and should be removed.

testinput_tier_1/stringmanipulation_obs.nc4 has more errors
testinput_tier_1/sattcwv_obs_20201230T0600Z.nc4 has more errors
testinput_tier_1/met_office_gauss_thinning_groundgnss_obs.nc4 has more errors

**Comment by orlewis** [comment]
Some of the validator tests still fail these are detailed below:
ctest -R ufo_data_validate_stringmanipulation_obs.nc4 -VV
1382:   Warning: Attribute 'odb_version' is present but is not listed as a required or optional attribute in the spec.
1382:   Warning: Attribute 'opsObsGroup' is present but is not listed as a required or optional attribute in the spec.
1382:   Warning: Attribute 'odb_version' does not have a YAML spec.
1382:   Warning: Attribute 'opsObsGroup' does not have a YAML spec.

ctest -R ufo_data_validate_sattcwv_obs_20201230T0600Z.nc4 -VV
1339:   Warning: Attribute 'date_time' is present but is not listed as a required or optional attribute in the spec.
1339:   Warning: Attribute 'opsObsGroup' is present but is not listed as a required or optional attribute in the spec.
1339:   Warning: Attribute 'opsObsGroup' does not have a YAML spec.

ctest -R ufo_data_validate_met_office_gauss_thinning_groundgnss_obs.nc4 -VV and ctest -R ufo_data_validate_met_office_gauss_thinning_groundgnss_obs.nc4 -VV

1291:    ERROR: Variable 'MetaData/thinningPriority' is not listed in the YAML conventions file.

Should thinning priority be included in the ObsSpace.yaml? @gthompsnJCSDA

**Comment by orlewis** [comment]
Updating the time to dateTime (secods since) has caused failures in the ufo_test_tier1_test_ufo_qc_gauss_thinning_ops ctest.

The files associated with this are
met_office_gauss_thinning_lon_-180_to_180_obs.nc4
met_office_gauss_thinning_lon_0_to_360_obs.nc4
met_office_gauss_thinning_groundgnss_obs.nc4

**Comment by orlewis** [comment]
The associated ctests are now passing apart from the one to validate met_office_gauss_thinning_groundgnss_obs.nc4. This can be explained through the ObsSpace.yaml not having the thinningPriority variable yet. 

ctest -R stringmanip
Test project /net/data/users/olewis/JEDI_branches/naming_conventions/build
    Start 1394: ufo_data_validate_stringmanipulation_obs.nc4
1/2 Test #1394: ufo_data_validate_stringmanipulation_obs.nc4 ..........   Passed    0.28 sec
    Start 1596: ufo_test_tier1_test_ufo_function_stringmanipulation
2/2 Test #1596: ufo_test_tier1_test_ufo_function_stringmanipulation ...   Passed    2.46 sec

100% tests passed, 0 tests failed out of 2


ctest -R groundgnss
Test project /net/data/users/olewis/JEDI_branches/naming_conventions/build
    Start 1216: ufo_data_validate_groundgnss_obs_2019123006_obs.nc
1/5 Test #1216: ufo_data_validate_groundgnss_obs_2019123006_obs.nc ...............   Passed    0.99 sec
    Start 1301: ufo_data_validate_met_office_gauss_thinning_groundgnss_obs.nc4
2/5 Test #1301: ufo_data_validate_met_office_gauss_thinning_groundgnss_obs.nc4 ...***Failed    0.23 sec
    Start 1636: ufo_test_tier1_test_ufo_opr_groundgnssmetoffice
3/5 Test #1636: ufo_test_tier1_test_ufo_opr_groundgnssmetoffice ..................   Passed    1.00 sec
    Start 1637: ufo_test_tier1_test_ufo_linopr_groundgnssmetoffice
4/5 Test #1637: ufo_test_tier1_test_ufo_linopr_groundgnssmetoffice ...............   Passed    0.90 sec
    Start 1638: ufo_test_tier1_test_ufo_opr_groundgnssropp
5/5 Test #1638: ufo_test_tier1_test_ufo_opr_groundgnssropp .......................   Passed    0.39 sec

80% tests passed, 1 tests failed out of 5


ctest -R ufo_data_validate_met_office_gauss_thinning_groundgnss_obs.nc4 -VV
1301:    ERROR: Variable 'MetaData/thinningPriority' is not listed in the YAML conventions file.
1301:   # errors:      1
1301:   # warnings:    0

ctest -R thinning_ops               
Test project /net/data/users/olewis/JEDI_branches/naming_conventions/build
    Start 1475: ufo_test_tier1_test_ufo_qc_gauss_thinning_ops
1/1 Test #1475: ufo_test_tier1_test_ufo_qc_gauss_thinning_ops ...   Passed    3.25 sec

100% tests passed, 0 tests failed out of 1

ctest -R satt
Test project /net/data/users/olewis/JEDI_branches/naming_conventions/build
    Start 1104: test_ioda-convert_sattcwv_odc
1/4 Test #1104: test_ioda-convert_sattcwv_odc ......................   Passed    0.24 sec
    Start 1349: ufo_data_validate_sattcwv_obs_20201230T0600Z.nc4
2/4 Test #1349: ufo_data_validate_sattcwv_obs_20201230T0600Z.nc4 ...   Passed    0.23 sec
    Start 1677: ufo_test_tier1_test_ufo_opr_sattcwv
3/4 Test #1677: ufo_test_tier1_test_ufo_opr_sattcwv ................   Passed    0.50 sec
    Start 1678: ufo_test_tier1_test_ufo_linopr_sattcwv
4/4 Test #1678: ufo_test_tier1_test_ufo_linopr_sattcwv .............   Passed    0.59 sec

100% tests passed, 0 tests failed out of 4


ctest -R aod_m
Test project /net/data/users/olewis/JEDI_branches/naming_conventions/build
    Start 1608: ufo_test_tier1_test_ufo_opr_aod_metoffice
1/2 Test #1608: ufo_test_tier1_test_ufo_opr_aod_metoffice ......   Passed    0.58 sec
    Start 1609: ufo_test_tier1_test_ufo_linopr_aod_metoffice
2/2 Test #1609: ufo_test_tier1_test_ufo_linopr_aod_metoffice ...   Passed    0.57 sec

100% tests passed, 0 tests failed out of 2

**Comment by BenjaminRuston** [comment]
@orlewis can you, or would you like me to close this PR and delete the branch.  It is no longer needed correct?

**Comment by orlewis** [comment]
> @orlewis can you, or would you like me to close this PR and delete the branch. It is no longer needed correct?

@BenjaminRuston This branch is still required. I have hand edited all of these files to ensure they pass all the ctests, removing variables that are not required etc.

**Comment by neill-b** [comment]
@orlewis - could you resolve the conflicts on this branch?

**Comment by BenjaminRuston** [comment]
@orlewis got it,,, assume you addressed Mike Cooke's comments 

did you resolve conflicts too?

**Review by mikecooke77 — APPROVED** [review]
Files look good.  Please add a dependency so that this is merged after #260

**Review by gthompsnJCSDA — APPROVED** [review]
@orlewis   One of the files did not yet have the change for `sequenceNumber` correct so I made the change and pushed it to your branch.  And I approve fully (THANKS!) and I will list your PR to merge *after* mine since you made more fixes such as `dateTime` in some files.

**Comment by fabiolrdiniz** [comment]
@orlewis, sorry for not asking before, but I had to commit something here to fix a conflict of files. Please, let me know if I broke something.

**Comment by orlewis** [comment]
> @orlewis, sorry for not asking before, but I had to commit something here to fix a conflict of files. Please, let me know if I broke something.

Something went wrong with the met_office_gauss_thinning_groundgnssnames_obs.nc4 file. Get a HDF5 error on an ncdump.

**Comment by gthompsnJCSDA** [comment]
> > @orlewis, sorry for not asking before, but I had to commit something here to fix a conflict of files. Please, let me know if I broke something.
> 
> Something went wrong with the met_office_gauss_thinning_groundgnssnames_obs.nc4 file. Get a HDF5 error on an ncdump.


Owen, could you try another `git pull` because it is working for me after an accidental commit earlier.  So I think it looks good again now.  Before git pull, ensure you are inside your branch, delete the file first, then git pull should replace it.  I needed to do that myself for it to become regular again.

**Pull request merged**
