### PR TITLE
Fix missing GeoVaLs/saturation_specific_humidity

### PR DESCRIPTION
**Pull request by delippi**
## Description

This PR fixes ctests related to the following PR by adding GeoVaLs/saturation_specific_humidity directly to the test data where needed. The GeoVaLs/saturation_specific_humidity were calculated from air_temperature and air_pressure GeoVaLs in the current geovals files according to how it is done in ufo using Eq2.17 and 2.19 from Rogers and Yau (1989).

```
The following tests previously FAILED and now PASS:
        1386 - ufo_test_tier1_instrument_aircraft_geos_qc (Pass)
        1391 - ufo_test_tier1_instrument_pibal_geos_qc (Pass)
        1398 - ufo_test_tier1_instrument_satwinds_geos_qc (Pass)

The following tests previously FAILED and still FAIL:
        1494 - ufo_test_tier1_test_ufo_qc_variableassignment (Failed)
```

## Dependencies

- https://github.com/JCSDA-internal/ufo/pull/3303

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by PatNichols — APPROVED** [review]
Thanks.

**Review by BenjaminRuston — APPROVED** [review]
still think this needs to be completed as a saturation_specific_humidity is not a GeoVaL that will be generically available so this ctest may pass but having the filter accurately depict it is needed but work should be coordinated and completed on a recipe to produce this GeoVaL

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by rtodling** [comment]
Geovals seem to have saturated_specific_humidity_profile  - I understand this is an odd name ... perhaps that's what this is! This is breaking things on GMAO's end ...

**Comment by delippi** [comment]
@rtodling, which geovals have saturated_specific_humidity_profile? I'm also curious what this is breaking.

**Comment by delippi** [comment]
> still think this needs to be completed as a saturation_specific_humidity is not a GeoVaL that will be generically available so this ctest may pass but having the filter accurately depict it is needed but work should be coordinated and completed on a recipe to produce this GeoVaL

@BenjaminRuston, I don't disagree. I just followed how this was done in other functions currently (e.g., ObsErrorSatSpecHumidity.cc). Maybe an issue should be opened to address this as well as in other functions as well?

**Pull request merged**
